feat: `WritingTable`, `WritingTablePage` 구현
woowacourse-teams/2023-dong-gle pull request #113
Opened 2023-07-27 07:29 UTC by yogjin

### 🛠️ Issue

- close #101 

### ✅ Tasks

https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/0b5aba37-994a-4173-8617-83c05b128977

- 카테고리 글 상세 목록 조회 api 추가
- 글 목록 테이블 `WritingTable` 추가
- `storybook`에서 `react-router-dom` 사용할 수 있도록`storybook-addon-react-router-v6` 설치
- 페이지 이동할 때 사용하는 `usePageNavigate` 훅 추가 
- `WritingTablePage`도 `WritingPage` 처럼 라우팅 처리
  - `usePageNavigate`가 반환하는 `goWritingTablePage(categoryId: number)` 함수 이용

### ⏰ Time Difference
- (6)+0

### 📝 Note
- `WritingTablePage`의 `S.Article`에 있는 border와 똑같은 스타일이 `WritingPage`에도 있어요.
  - 테두리 부분을 `Layout` 에서 한번에 사용할 수 있을지.. 고민중입니다. 
  - 아니면 저 스타일을 styled-components `css`변수로 빼서 재사용하도록 해도 좋을 것 같네요.
- 실제 동작 해보려면 버튼 하나 만들어서 클릭 핸들러로 `goWritingTablePage` 함수 적용하시면 됩니다.

2023-07-27 08:53 UTC, jeonjeunghoon reviewed
궁금한 점 코멘트 남겼어요 고생하셨어요

2023-07-27 08:53 UTC, jeonjeunghoon commented on frontend/src/types/apis/writings.ts
> +};
<img width="662" alt="스크린샷 2023-07-27 오후 5 05 57" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/843b67a4-9345-4650-968e-090ac0ea95a9">

명세랑 좀 다른 것같아요! 혹시 제가 업뎃이 안된건가요?

2023-07-27 08:53 UTC, jeonjeunghoon commented on frontend/src/types/apis/writings.ts
> +};
<img width="664" alt="스크린샷 2023-07-27 오후 5 08 58" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/e67c4333-5101-43eb-8ac2-b099b31dbdfd">

아 혹시 이건가요?

2023-07-27 08:53 UTC, jeonjeunghoon commented on frontend/src/types/apis/writings.ts
> +};
제가 착각한거같네요 ㅎㅎ

2023-07-27 08:53 UTC, jeonjeunghoon commented on frontend/src/components/WritingTable/WritingTable.tsx
> +  };
```typescript
const BLOG_ICONS: Blog = {
  MEDIUM: <MediumLogoIcon width='2.4rem' height='2.4rem' />,
  TISTORY: <TistoryLogoIcon width='2.4rem' height='2.4rem' />,
  };
```

혹시 이런 형태는 좋지 못한 패턴인가요? (궁금해서 물어보는거)

2023-07-27 08:53 UTC, jeonjeunghoon commented on frontend/src/utils/date.ts
> +};
이 부분 `switch` 쓴 이유 궁금해요 다른 형식의 날짜를 대비하기 위함인가요?

2023-07-27 08:53 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +    background-color: ${({ theme }) => theme.color.gray1};
`padding`만 제외하곤 똑같아서 레이아웃 부분에서 분리해서 재사용 가능할 것같아요

2023-07-28 06:50 UTC, nangkyeonglim requested changes
고생하셨습니다 쿠마~!
그리고 페이지는 내용물만 오고 border는 layout으로 분리하는 게 좋을 것 같아요!
코멘트 확인해주세요~

2023-07-28 06:50 UTC, nangkyeonglim commented on frontend/src/components/WritingTable/WritingTable.tsx
> +          <col style={{ width: '20%' }} />
```suggestion
          <col width='60%' />
          <col width='20%' />
          <col width='20%' />
```
이거 col 기본 속성에 width가 있는데 이렇게 쓰는 것은 어떨까요?

2023-07-28 06:50 UTC, nangkyeonglim commented on frontend/src/components/WritingTable/WritingTable.tsx
> +    <>
Fragment 없어도 될 것 같습니다

2023-07-28 06:50 UTC, nangkyeonglim commented on frontend/src/components/WritingTable/WritingTable.tsx
> +          {writings.map((writing) => (
```suggestion
         {writings.map(({ id, title, publishedDetails, createdAt }) => (
```
밑에 구조분해 할당쓰는 거 어떻습니까

2023-07-28 06:50 UTC, nangkyeonglim commented on frontend/src/components/WritingTable/WritingTable.tsx
> +                <div className='publishedTo'>
이 div styled-component로 만들면 className이랑 밑에 스타일에도 중첩으로 쓰지 않아도 될 것 같아요

2023-07-28 06:50 UTC, nangkyeonglim commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +type Props = {};
이거 안지운건가요 의도한건가요?!

2023-07-28 17:34 UTC, yogjin commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +type Props = {};
안지웠네요😅

2023-07-28 17:36 UTC, yogjin commented on frontend/src/components/WritingTable/WritingTable.tsx
> +                <div className='publishedTo'>
오.. 좋은데요?
반영했습니다

2023-07-28 17:36 UTC, yogjin commented on frontend/src/components/WritingTable/WritingTable.tsx
> +          {writings.map((writing) => (
오.. 좋은데요?
반영했습니다

2023-07-28 17:53 UTC, yogjin commented on frontend/src/components/WritingTable/WritingTable.tsx
> +          <col style={{ width: '20%' }} />
오 이건 몰랐네요.
반영했습니다!

2023-07-28 17:56 UTC, yogjin commented on frontend/src/assets/icons/tistory-logo.svg
아니요 어떤 블로그에서 가져온거에요.
https://injeblog.tistory.com/86 여기 색상 있는걸로 바꿀까요?

2023-07-28 17:59 UTC, yogjin commented on frontend/src/utils/date.ts
> +};
네 맞아요 다른 `format`이 생기면 `case`를 추가하면 됩니다~

2023-07-28 18:04 UTC, yogjin commented on frontend/src/components/WritingTable/WritingTable.tsx
> +  };
오 좋은데요?
반영했습니다.
7f0815935dfdb383deca848fe6306ef6ea0cb960

2023-07-28 18:05 UTC, yogjin commented on frontend/src/components/WritingTable/WritingTable.tsx
> +  };
오 좋은데요?
7f0815935dfdb383deca848fe6306ef6ea0cb960

2023-07-28 18:10 UTC, yogjin commented on frontend/src/components/WritingTable/WritingTable.tsx
> +                <div className='publishedTo'>
흠.. 바꾼게 더 낫네요 ㅋㅋㅋㅋㅋ
반영했습니다~
2060f0d60a6d56064a7625ff94db097996a02f5d

2023-07-28 18:15 UTC, yogjin commented
> 그리고 페이지는 내용물만 오고 border는 layout으로 분리하는 게 좋을 것 같아요!

이거 반영하고 싶은데.. 
지금 건드리면 https://github.com/woowacourse-teams/2023-dong-gle/pull/120 스타일과 충돌 많이 날 것 같아서 나중에 리팩터링 하겠습니다😁

2023-07-29 07:59 UTC, nangkyeonglim commented on frontend/src/assets/icons/tistory-logo.svg
굿!

2023-07-29 08:00 UTC, nangkyeonglim commented
반영한 거 확인했습니다~! approve 할게요

2023-07-29 08:00 UTC, nangkyeonglim approved these changes

2023-07-30 06:16 UTC, jeonjeunghoon commented
반영까지 고생 많으셨어요!!

2023-07-30 06:16 UTC, jeonjeunghoon approved these changes
반영까지 고생 많으셨어요!

2023-07-30 06:39 UTC, merged