[FE] feat: `Tag` 컴포넌트 구현
woowacourse-teams/2023-dong-gle pull request #118
Opened 2023-07-27 14:30 UTC by nangkyeonglim

### 🛠️ Issue

- close #103 

### ✅ Tasks
- Tag 컴포넌트 구현
- Tag 스토리북 작성

### ⏰ Time Difference
- 4(-2)

### 📝 Note
- 태그 컴포넌트는 발행 정보에 태그 입력 시 사용될 수 있고, 아래처럼 글 정보에 발행된 태그의 정보를 볼 때도 사용할 수 있습니다.

![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/aa6ec74a-14b8-49f0-8620-4d8fcc2cc468)

따라서 태그의 용도는 태그 입력(편집)시, 혹은 태그를 조회할 때의 용도로 사용할 수 있다고 생각을 했습니다.

![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/9e92cf31-711c-4d94-b882-f33f938a19a6)

그래서 다음과 같이 `removable` props를 두어서 삭제가 가능한 태그라면 close 아이콘도 함께 보이도록 만들었습니다.
Tag 삭제할 때 close 아이콘 뿐만이 아닌 태그 내부 아무데나 눌러도 삭제 가능하게 하고 싶어서 Tag 전체를 button으로 만들었습니다.

태그 삭제 시에는 외부에서 onClick 할 때 삭제 로직을 넣어주면 될 것이고, 태그를 조회하는 용도일 때는 onClick에 해당 태그에 해당하는 글들을 보여주는 로직을 넣는 식으로 나중에 사용할 수 있을 것 같아요.

2023-07-27 14:50 UTC, jeonjeunghoon approved these changes
깔끔하네요~ 고생하셨어요 👍

2023-07-28 16:37 UTC, yogjin requested changes
너무 좋습니다~ 코멘트 하나 남겨두었어요!

2023-07-28 16:37 UTC, yogjin commented on frontend/src/components/@common/Tag/Tag.tsx
> +export default Tag;
```suggestion
const Tag = ({ removable = true, children, ...rest }: Props) => {
  const [isShow, setIsShow] = useState(true);

  return (
    isShow && (
      <S.Tag {...rest} onClick={() => removable && setIsShow(false)}>
        #{children}
        {removable && <CloseRounded width={14} height={14} />}
      </S.Tag>
    )
  );
};
```
다음과 같이 `removable`이 `true` 일 때 내부적으로 태그를 삭제하도록 하면 어떨까요? 외부에서 삭제하는 로직을 받는게 살짝 어색하게 느껴져서 한번 제안해봅니다!

2023-07-29 18:49 UTC, nangkyeonglim commented on frontend/src/components/@common/Tag/Tag.tsx
> +export default Tag;
음 생각은 해봤는데요
일단 제가 생각했을 때는 TagInput이라는 컴포넌트가 Tag 추가 삭제 수정 로직을 가지고 있고, Tag 자체는 그냥 글 정보에서도 사용할 수 있고 TagInput에서도 사용할 수 있는 공용 컴포넌트라는 생각을 했어요.

TagInput에서 모든 추가,삭제,수정 로직을 가지고 있기에 오히려 Tag에 삭제 로직만 있으니까 약간 로직이 분산되어 버리더라구요
아니면 오히려 여기서 removable prop과 Close 아이콘을 없애고 TagInput쪽에서 Close 아이콘을 같이 넣어주는 건 어떤가요?

```suggestion
const Tag = ({ children, ...rest }: Props) => {
  return (
    <S.Tag {...rest}>#{children}</S.Tag>
  );
};

export default Tag;
```

![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/19344168-dd1a-4378-a7f3-52268726c956)

2023-07-30 05:29 UTC, yogjin commented on frontend/src/components/@common/Tag/Tag.tsx
> +export default Tag;
음 그 이유라면 `removable` 일 때 삭제 아이콘만 추가시켜주는 기존 것도 좋아보입니다!

2023-07-30 05:30 UTC, yogjin approved these changes

2023-07-30 05:34 UTC, merged