Feature/accordion 99
woowacourse-teams/2023-dong-gle pull request #119
Opened 2023-07-27 16:43 UTC by jeonjeunghoon

### 🛠️ Issue

- close #99 

### ✅ Tasks

- [x] 아코디언 컴포넌트 구현
  - [x] 외부에서 [제목, 내용] 튜플 배열을 받는 방법으로 수정
  - [x] 글 목록이 비어있을 때 처리
  - [x] HeaderButton 컴포넌트 내 header를 감싸는 p태그 삭제
  ```tsx
    return (
      <S.Button {...rest}>
      ...
          <p>{header}</p>
      ...
      </S.Button>
    );
  ```
- [x] 아코디언 스토리북 작성

### ⏰ Time Difference
- (4)+7

### 📝 Note

![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/da0a6412-f95c-4ef2-8edb-b37624b6b6ff)

- UI: 동글 카테고리를 보니 아코디언 자체엔 디자인이 거의 없어서 기능 + 애니메이션에 신경쓰며 구현했습니다.
- 구조: 합성 컴포넌트로 구현해보려 하다가, 그렇게 구현하면 아코디언 컴포넌트를 사용할 때 불편할 것같아 컴파운드 패턴은 포기했습니다. 그러나 지금 사용법도 편한지 모르겠습니다.

사용법

**구상했던 컴파운드 패턴 아코디언 사용법**
```tsx

// title: ReactNode[]
// panel: ReactNode[]
// 타이틀 || 패널 클릭 핸들러(optional): () => void

<Accordion>
  {[title[], panel[]].map(([title, panel) => {
    return (
      <Accordion.Item>
        <Accordion.Title title={title} onTitleClick={ ~ } />
        <Accordion.Panel panel={panel} onPanelClick={ ~ } />
      </Accordion.Item>
    )}
</Accordion>
```

**아커디언 컴포넌트 사용법**
```tsx

// accordionContents: [ReactNode, ReactNode][]

<Accordion accordionContents={accordionContents} onTitleClick={ ~ } onPanelClick={ ~ } />
```

고민이네용

2023-07-29 18:18 UTC, nangkyeonglim requested changes
아커 여러 번 갈아엎고 고생많으셨습니다..
컴파운드 패턴을 한번도 안써봐서 잘 몰랐는데 덕분에 알아갑니다
몇 개 질문과 코멘트 남겼으니 확인부탁드려요!

2023-07-29 18:18 UTC, nangkyeonglim commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    dark: css`
근데 이거 다크가 왜 있는 거죠?! 나중에 다크모드를 위한거라면 style/theme에서 전체적으로 추가할 수 있을 거 같아요

2023-07-29 18:18 UTC, nangkyeonglim commented on frontend/src/components/@common/Accordion/AccordionItem.tsx
> +            onClickIcon: () => isSetOpen(!isOpen),
이거 바로 setter를 실행하지 않고 togglePanel 이런식으로 함수로 분리해서 사용할 수 있을 거 같아요! 
onClickIcon도 onToggleIconClick 이런식으로 명확하게 가면 좋을 것 같아요!

2023-07-29 18:18 UTC, nangkyeonglim commented on frontend/src/components/@common/Accordion/AccordionTitle.tsx
> +    if (onClick) onClick();
이게 어떤 건지 잘 이해가 안되는데 혹시 아이콘이 있으면 onCllickIcon 없으면 onClick을 실행하기 위함인가요?

2023-07-31 05:42 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/Accordion.stories.tsx
> +export const Playground: Story = {};
스토리 동작하게 수정했습니다!

2023-07-31 05:59 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    ${({ variant = 'primary' }) => generateVariantStyle(variant)};
`Partial` 을 사용해봤는데, 그래도 타입에 `undefined` 가 추론되서 안되더라구요 ... 그래서 일단 default props 넘겨 주는 방식으로 냅뒀습니다.

2023-07-31 05:59 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    dark: css`
해당 항목 삭제했습니다 ㅎㅎ

2023-07-31 07:25 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/AccordionItem.tsx
> +            onClickIcon: () => isSetOpen(!isOpen),
`togglePanel` 함수로 분리했습니다!

2023-07-31 07:27 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/AccordionItem.tsx
> +            onClickIcon: () => isSetOpen(!isOpen),
또한 Title 에서 받는 핸들러 props 네이밍은 `onToggleIconClick` 로 수정했습니다

2023-07-31 07:28 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/AccordionTitle.tsx
> +    if (onClick) onClick();
로직을 분리했어야 했는데, 깜빡했네요 😅

`onClickIcon` (현재는 `onToggleIconClick`)은 토글 로직이구요
`onClick`(현재는 `onTitleClick`)은 아코디언에 넘겨주는 이벤트 핸들러입니다~ 저희 도메인에서는 카테고리 테이블 페이지로 넘어가는 로직이 들어갈 것같아요.

2023-07-31 07:34 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    ${({ variant = 'primary' }) => generateVariantStyle(variant)};
optional을 빼면 사용처에서 무조건 넣어줘야해서 못 뺄 것같아요 .....

2023-07-31 09:07 UTC, nangkyeonglim commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    ${({ variant = 'primary' }) => generateVariantStyle(variant)};
위에서 옵셔널 빼고 밑에 Partial로 바꾸고 suggested Change 해도 안되던가요..?

2023-07-31 12:53 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    ${({ variant = 'primary' }) => generateVariantStyle(variant)};
오 잘돼요 제가 아까 뭔가 안지웠나봐요.

2023-07-31 12:58 UTC, nangkyeonglim commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    ${({ variant = 'primary' }) => generateVariantStyle(variant)};
오 좋습니다👍

2023-07-31 13:01 UTC, nangkyeonglim requested changes

2023-07-31 13:45 UTC, yogjin commented on frontend/src/components/@common/Accordion/AccordionItem.tsx
> +};
추후 context 만들어서 provider로 감싸고, panel 과 title에서 이용하는게 좋을 것 같아요

2023-07-31 13:48 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/AccordionTitle.tsx
> +    <S.Container onClick={() => onTitleClick}>
앗 오타가 있었네요 감사합니다

2023-07-31 13:48 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +const generateAccordionSize = (size: Required<Props>['size']): RuleSet<object> => {
넵!

2023-07-31 13:48 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/Accordion.tsx
> +    `,
넵 그렇게 수정하겠습니다.

2023-07-31 13:48 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/AccordionItem.tsx
> +  const [isOpen, isSetOpen] = useState(false);
아이고 오타가 있었네요 감사합니다

2023-07-31 13:48 UTC, jeonjeunghoon commented on frontend/src/components/@common/Accordion/AccordionItem.tsx
> +};
넵 이후에 context로 리팩토링 하는게 좋은 것같아요.

2023-07-31 16:02 UTC, nangkyeonglim approved these changes
확인했습니다 고생하셨어요!

2023-07-31 16:46 UTC, yogjin approved these changes
수고하셨어요

2023-07-31 16:57 UTC, merged