[FE] feat: `Header` 컴포넌트 구현
woowacourse-teams/2023-dong-gle pull request #120
Opened 2023-07-27 17:00 UTC by yogjin

### 🛠️ Issue

- close #102 

### ✅ Tasks

https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/8b3b12eb-a24d-4b65-a77c-1780a4877a75

- 맨 위 `Header` 컴포넌트 구현
- 왼쪽, 오른쪽 사이드바 열고 닫히는 기능 추가

### ⏰ Time Difference
-  (4)+0

### 📝 Note
- 소소한 버그1: 시안에는 `WritingTablePage`에 오른쪽 사이드바가 없지만 헤더의 오른쪽 사이드바 아이콘을 클릭하면 메인페이지 width가 줄어듭니다.
  - 현재 사이드바 컴포넌트가 구현되지 않고 각 Page에 종속적이기 때문에 아직 감이 잘 안오네요. 
  - `WritingTablePage`의 오른쪽 사이드바가 추후 추가될 여지도 있기 때문에 일단 이 상태로 나뒀습니다. 
- 소소한 버그2: 영상보면 아시겠지만 글 목록이 잘 불러와졌을 때 헤더 height가 깨지고 `Layout` 스타일도 깨지네요. 알아보고 고치겠습니다.
- ark 브라우저나 노션, 옵시디언처럼 사이드바가 자연스럽게 나왔다가 숨겨지는 애니매이션을 구현하고 싶었는데, display:none은 transition이 안먹어서 일단 보류했습니다.. 다른 중요한 이슈들 먼저 끝내고 시도해볼게요.
- `useOutletContext`에 대한 내용은 [공식문서](https://reactrouter.com/en/main/hooks/use-outlet-context)를 참고해주세요.
- 아직 머지되지 않은 #101에서 브랜치를 팠기 때문에 현재 커밋이 101번 이슈 것 까지 포함되어 있습니다.

2023-07-28 09:30 UTC, nangkyeonglim requested changes
헤더가 줄어드는 오류랑 오른쪽 사이드바가 존재 하지 않을때는 오른쪽 사이드바 아이콘도 없어도 될 것 같아요~!

2023-07-28 09:30 UTC, nangkyeonglim commented on frontend/src/pages/Layout/Layout.tsx
> +  const [isRightSidebarOpen, setIsRightSidebarOpen] = useState(false);
일단 기본적으로 true로 주는 게 좋을 것 같아요! 나중에는 로컬스토리지 사용해서 사용자 설정대로 하는 것도 좋겠네욥

2023-07-30 08:27 UTC, yogjin commented on frontend/src/styles/layoutStyle.ts
> +    (isLeftSidebarOpen === false && isRightSidebarOpen === true) ||
의도한 건 아닙니다
그와 별개로 저 스타일 상수(`genMainPageWidth`)는 사용하지 않는 것으로 변경되어 삭제했습니다!

2023-07-30 08:32 UTC, yogjin commented on frontend/src/components/Header/Header.tsx
> +      <div className='left'>
제가 최근 `className`에 빠져있었던 거 같아요 ㅋㅋㅋ
수정했습니다~

2023-07-30 11:38 UTC, yogjin commented on frontend/src/components/Header/Header.tsx
> +        <SettingIcon width='2.4rem' height='2.4rem' className='icon' />
잘 몰랐는데, 웹 접근성을 고려해서라도 바꾸는게 좋겠네요

2023-07-30 11:51 UTC, yogjin commented on frontend/src/pages/Layout/Layout.tsx
> +  return useOutletContext<PageContextType>();
`useOutletContext`은 `Outlet`에 필요한 Context를 편하게 사용할 수 있는 react-router-dom 메서드입니다.
리액트의 기존 useContext를 이용할 수도 있겠지만, 1. `<Outlet/>`을 `context.Provider`로 감싸야하고 2. context 내부에서 (context를 사용하는 컴포넌트가 context.Provider로 감싸져있는지) 에러핸들링도 해야합니다. 따라서 이렇게 번거로운 일을 할 필요없이 `useOutletContext`를 이용한다면 `<Outlet/>` 에 `context` prop만 넘겨주는 것으로 쉽게 목적을 달성할 수 있어서 사용했습니다.

2023-07-30 12:06 UTC, yogjin commented on frontend/src/pages/Layout/Layout.tsx
> +          <Button onClick={() => goWritingTablePage(1)}>ㅋㅋ</Button>
아 이거 임시코드인데.. 같이 들어가버렸네요
마지막에 다 합칠때 지우면 되니깐 일단 시연하기 쉽게 놔둘게요~

2023-07-30 12:25 UTC, nangkyeonglim commented on frontend/src/components/Header/Header.tsx
> +      <div className='left'>
ㅋㅋㅋㅋ 좋아요

2023-07-30 12:27 UTC, nangkyeonglim commented on frontend/src/pages/Layout/Layout.tsx
> +  return useOutletContext<PageContextType>();
오 덕분에 알아갑니다👍

2023-07-30 18:08 UTC, nangkyeonglim approved these changes
이거 두개만 수정해주세요!

2023-07-30 18:08 UTC, nangkyeonglim commented on frontend/src/pages/Layout/Layout.tsx
> +  const [activeWritingId, setActiveWritingId] = useState<number>(-1);
이거 저희 컨벤션 따라 null 수정해주세요!

2023-07-31 05:02 UTC, jeonjeunghoon reviewed
구현하시느라 고생 많으셨습니다~!
코멘트 확인부탁드려용

2023-07-31 05:02 UTC, jeonjeunghoon commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    <>
이거 없어도 될 것같아요!

2023-07-31 07:33 UTC, yogjin commented on frontend/src/pages/Layout/Layout.tsx
> +              } satisfies PageContextType
context prop에 들어간 객체에 key의 네이밍이 `PageContextType`과 똑같도록 강제하기 위해서 사용했습니다.
네이밍이 다르다면 `usePageContext`를 사용하는 쪽에서 context 값이 `undefined`가 되기때문에, 저렇게 satisfies를 이용해 런타임 에러를 방지했습니다.

+ `usePageContext`는 따로 제네릭을 넣을 수 없더라구요. 저렇게 타입을 검증하는 게 가장 안전하고 간단한 방법인 것 같습니다.

2023-07-31 07:35 UTC, jeonjeunghoon commented on frontend/src/pages/Layout/Layout.tsx
> +              } satisfies PageContextType
아하 이해됐습니다 ㅎㅎ

2023-07-31 10:32 UTC, jeonjeunghoon approved these changes

2023-07-31 10:32 UTC, merged