[BE] 엔티티 리팩터링
woowacourse-teams/2023-dong-gle pull request #123
Opened 2023-07-28 05:41 UTC by HubCreator

### 🛠️ Issue

- close #109 

### ✅ Tasks
- block과 content 간의 cascade 설정
- 엔티티 내부 필드 객체화

### ⏰ Time Difference
- 1 -> 4

2023-07-29 04:40 UTC, ingpyo approved these changes

2023-07-29 04:40 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/DonggleApplication.java
> +        SpringApplication.run(DonggleApplication.class, args);
멋지네요

2023-07-29 04:40 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/application/repository/BlockRepository.java
> +    @EntityGraph(attributePaths = {"content"})
EAGER로딩으로 바꿔서 EntityGraph을 삭제하는게 어떨까요? 개인적인 의견입니다...

2023-07-29 04:40 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/application/service/WritingService.java
> +            blockRepository.save(new Block(savedWriting, content));
stream을 사용해보는게 오떨까요?

2023-07-29 04:40 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/domain/member/Member.java
>      private Long id;
id어노테이션이 빠져있는거같아요

2023-07-29 04:40 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownParser.java
> +        return Depth.from(depthCount);
```
 Matcher matcher = Pattern.compile(DEPTH_SPLIT_REGEX).matcher(textBlock);

    final long depthCount = matcher.results()
        .map(result -> result.group(0))
        .filter(match -> !match.isEmpty())
        .count();

    return Depth.from((int) depthCount);
```
이런식으로 바꿀 수 있을거같아요

2023-07-29 04:40 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/domain/writing/StyleIndex.java
> +public class StyleIndex {
start,endIndex(int)를 한번에 가지고있는 IndexRange라는 객체를 만들면 어떨까요? 시작과 끝점은 단독으로 안사용할거같아서용

2023-07-29 08:23 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/repository/BlockRepository.java
> +    @EntityGraph(attributePaths = {"content"})
현재 `Block`과 `Content`가 일대일 단방향 관계로 매핑되어 있습니다. 또한 연관관계의 주인은 `Block`인 상황입니다. 일단 페어 프로그래밍을 진행하면서 `Block`에서 `Content`를 LAZY로 관리하도록 둔 이유는 다음과 같아요!

우리가 `Block`과 `Content`를 하나로 합칠 수 있음에도 불구하고 일대일로 객체를 나눈 이유는 관심사를 분리하자! 였던 걸로 이해하고 있습니다.  나중에 Block 쪽에만 정보가 추가될 수 있다고 가정했었죠. 예를 들어 `Block`간의 순서 정보가 있겠네요. 이럴 때 `Content`는 독립적으로 관리면 좋을 것이다! 라고 얘기가 나와서 현재의 구조가 만들어진 것으로 보고 있습니다.

그렇다면 `Block`에만 있는 정보를 언젠가는 필요로 할텐데, 이때 `Content`가 꼭 필요하지 않은 상황이 있을 것 같아요. 예를 들어 `Block`의 순서만 변경한다든지, `Block`에 있는 `Writing` 정보만을 바꾼다든지 할 때에는 `Content`를 꼭 EAGER하게 가져오지 않아도 될 것이라고 판단했어요. 필요하지 않은 상황에서도 불필요하게 가져올 수 있기 때문이죠.

그래서 페어와 생각해본 결과, 위의 상황들이 생길 수 있다고 판단했기에 기본적인 설정은 LAZY로 두고 `Block`을 가져올 때 `Conetnt`가 필요할 때에만 fetch join하여 땡겨오자! 라고 결론 지었습니다.

위와 같이 생각해서 LAZY로 두었는데, 우리의 생각이 합당한 생각이었는지 비버의 의견도 듣고 싶네요 ㅎㅎㅎ

2023-07-29 08:39 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/WritingService.java
> +            blockRepository.save(new Block(savedWriting, content));
좋아요! 매 번 돌면서 save를 날리는 것 보다 batchInsert를 하도록 바꿔봤습니다!

```java
final List<Block> blocks = contents.stream()
                .map(content -> new Block(savedWriting, content))
                .toList();

blockRepository.saveAll(blocks);
```

2023-07-29 08:52 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownParser.java
> +        return Depth.from(depthCount);
현재 `while` 문 안에서 `textBlock`과 `matcher`값을 계속해서 변경해 나가고 있는 구조입니다. 스트림은 데이터 소스로부터 데이터를 읽기만할 뿐, 기존의 데이터를 변경할 수 없다고 알고 있는데 현재의 구조에서 반영할 수 있을지 생각이 잘 안떠오르네요ㅠㅠㅠ

2023-07-29 09:11 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/domain/writing/StyleIndex.java
> +public class StyleIndex {
진짜 너무 좋아요... 고마워요 :)

2023-07-29 12:16 UTC, echo724 requested changes
수고많았어요! 저는 대부분 스타일 적인 거고 검증 부분 몇개만 리뷰 달았습니다~!

2023-07-29 12:16 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownParser.java
> +        String removedDepthText = removeDepth(depth.getDepth(), textBlock);
자잘한거긴 한데, 메서드 내에서 원시값을 까주는건 어떨까 싶네요!

2023-07-29 12:16 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/domain/parser/markdown/MarkDownParser.java
> +                return new NormalContent(depth, blockType, new RawText(removedStyleTypeText), styles);
이것도 스타일적인거긴 한데 정팩메로 원시값을 받는 메서드를 열어두는건 어떨까요!?

2023-07-29 12:16 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/domain/member/Email.java
> +    private String email;
이메일 형식에 관한 검증도 필요할 것 같습니다! TODO로 남겨두고 다음 리팩토링때 적용해봐도 좋을 것 같네요! 아니면 import jakarta.validation.constraints.Email; 어노테이션을 달면 이메일 검증이 된다고 합니다!

2023-07-29 12:16 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/domain/writing/StyleRange.java
> +    private void validateIndex(final int startIndex, final int endIndex) {
startIndex > endIndex인 경우도 검증해줘야할 것 같네요!

2023-07-29 12:16 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/ui/WritingController.java
> +    public ResponseEntity<Void> writingAdd(final MultipartFile file) throws IOException {
오 좋은 분리인 것 같습니다!

2023-07-29 12:16 UTC, echo724 approved these changes

2023-07-29 14:42 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/domain/member/Email.java
> +    private String email;
요 이슈는 월요일날 다시 말씀드릴게요!

2023-07-29 14:45 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/domain/writing/StyleRange.java
> +    private void validateIndex(final int startIndex, final int endIndex) {
제가 놓쳤네요! 감사합니당

2023-07-30 07:18 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/application/repository/BlockRepository.java
> +    @EntityGraph(attributePaths = {"content"})
처음에는 
>우리가 Block과 Content를 하나로 합칠 수 있음에도 불구하고 일대일로 객체를 나눈 이유는 관심사를 분리하자! 였던 걸로 이해하고 있습니다. 나중에 Block 쪽에만 정보가 추가될 수 있다고 가정했었죠. 예를 들어 Block간의 순서 정보가 있겠네요. 이럴 때 Content는 독립적으로 관리면 좋을 것이다! 라고 얘기가 나와서 현재의 구조가 만들어진 것으로 보고 있습니다.

이렇게 구조를 만들었는데 프록시객체 때문에 `@EntityGraph(attributePaths = {"content"})` 이부분을 추가해서
무조건 EAGER로딩으로 가져오는걸로 알고있습니다...
그래서 제 생각은 무조건 EAGER로 가져오면 `@EntityGraph(attributePaths = {"content"})`이부분을 삭제하고 interface를 볼 필요없이 객체를 확인하면 즉시로딩이구나 생각할 수 있을거같아요.

2023-07-30 08:16 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/repository/BlockRepository.java
> +    @EntityGraph(attributePaths = {"content"})
EAGER로 설정한다면, 이에 대한 전제는 "모든 경우에 있어서 `Block`을 가져올 때 반드시 `Content`의 정보도 필요하다!" 라는 것 같아요. 요부분에 대해서는 월요일날 조금 더 얘기해보면 좋을 것 같네요 ㅎㅎㅎ

2023-07-30 08:18 UTC, merged