[FE] 카테고리 컴포넌트 구현
woowacourse-teams/2023-dong-gle pull request #126
Opened 2023-07-29 06:32 UTC by jeonjeunghoon

### 🛠️ Issue

- close #100 

### ✅ Tasks
- [x] 카테고리 컴포넌트 구현
- [x] 카테고리 내부 글 컴포넌트 구현
- [x] 카테고리 섹션 컴포넌트 구현
- [x] 카테고리 추가 기능 fetcher 구현
- [x] 카테고리 삭제 기능 구현
- [x] 카테고리 이름 수정 기능 구현 (낙관적 업데이트)

### ⏰ Time Difference
- (4) + 10

### 📝 Note
- API 통신이 안돼서 섹션까지는 정확한 테스트가 안됩니다.
- 카테고리 이름 수정은 낙관적 업데이트 방식을 적용했는데, 추가나 삭제에도 똑같이 적용해야할까요?
- 예상보다 더 늦은 시간이 걸려 죄송합니다. 생각보다 많이 어려웠네요.

2023-07-29 17:45 UTC, nangkyeonglim requested changes
아커 고민한 흔적이 많이 보이네요!
파일이 좀 많아서 리뷰하는데 시간이 좀 걸렸습니다😹

2023-07-29 17:45 UTC, nangkyeonglim commented on frontend/src/hooks/useWritingsInCategory.ts
> +
이 부분 때문에 useQuery 수정 얘기가 나왔나 보군요?! 
찾아보니 useQuery에는 enabled 옵션이 있더라고요.

이런 경우처럼 [dependent query](https://tanstack.com/query/latest/docs/react/guides/dependent-queries)가 필요한 경우에 바로 fetch해오지 않는 옵션인데 저희 훅에서는 변경이 필요하겠네요,,

2023-07-29 17:45 UTC, nangkyeonglim commented on frontend/src/hooks/useWritingsInCategory.ts
> +      : Promise.reject('No Category ID');
```suggestion
    return categoryId 
      ? getWritingsInCategory(categoryId)
      : Promise.reject('No Category ID');
```

2023-07-29 17:45 UTC, nangkyeonglim commented on frontend/src/components/Category/Category.tsx
> +    }
```jsx
 &:hover ${IconContainer}{
  display: flex;
  gap: 0.4rem;
}
```
원래 스타일드 컴포넌트 이런식으로 편리하게 쓸 수 있는데 저희가 S로 한번에 묶어서 이게 안되네요,,?! 이런 단점이..

2023-07-29 17:45 UTC, nangkyeonglim commented on frontend/src/components/Category/Category.tsx
> +    }
이거 쿠마 리뷰에도 남겼지만 Icon에 버튼 기능이 필요하면 button으로 감싸는 게 좋을 것 같아요
semantic tag + button에 전역으로 cursor:pointer 달려있고 onClick을 icon에 달아도 그 접근성 테스트 어제 해봤었는데 tab으로 인식이 안되더라구요

+) 전체적으로 icon 버튼이 많이 사용되고있는데 공통 컴포넌트를 만드는 것도 좋을 것 같습니다 혹은 이미 만들어져있는 공통 Button 컴포넌트로도 만들수 있을 것 같긴하네여

2023-07-29 17:45 UTC, nangkyeonglim commented on frontend/src/components/Category/Category.tsx
> +        <DeleteIcon onClick={handleTrashcanIconClick} width={12} height={12} />
이 친구들 onClick 네이밍 renameCategory, deleteCategory처럼 명확히 네이밍 하는 것은 어떨까요?

2023-07-29 17:45 UTC, nangkyeonglim commented on frontend/src/hooks/useCategoryName.ts
> +    setRename(() => '');
이거 혹시 콜백함수로 쓴 이유가 있을까요?

2023-07-29 17:45 UTC, nangkyeonglim commented on frontend/src/components/Category/Category.tsx
> +          onKeyUp={requestChangedName}
input에서 onBlur될 때 그대로 input 창이 남아버리는데 이 경우 원래 이름으로 바꿔준다던지, 아니면 수정하고 있던 이름으로 바꿔준다던지 하는 것이 좋을 것 같아요!

2023-07-31 11:18 UTC, jeonjeunghoon commented on frontend/src/mocks/categoryContentsMock.ts
> +    },
`5. 카테고리 목록 조회 : GET` < 이거 말씀하시는거 맞나요?

백엔드에게 확인해보니 이대로 온다고 하네용

2023-07-31 12:56 UTC, nangkyeonglim commented on frontend/src/mocks/categoryContentsMock.ts
> +    },
아 그래요? 알겠습니다~!

2023-07-31 19:04 UTC, jeonjeunghoon commented on frontend/src/components/Category/WritingsInCategory.tsx
> +const WritingsInCategory = ({ writings }: Props) => {
`WritingList` 로 수정했습니다~!

2023-07-31 19:04 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.stories.tsx
> +      '가나다라마바사아자차카타파하가나다라마바사아자차카타파하가나다라마바사아자차카타파하가나다라마바사아자차카타파하가나다라마바사아자차카타파하',
앗 flex를 줘야겠군요

2023-07-31 19:19 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.stories.tsx
> +};
이전 기획 때문에 작성한 스토리인데 미처 삭제하지 못했네요 ㅎㅎ ... 지금은 삭제했습니다!

2023-08-01 04:54 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.tsx
> +const Category = ({ id, categoryName }: CategoryResponse) => {
확장성을 위해 필요한 방법인 것같네요! 말씀하신대로 바꿨습니다.

2023-08-01 04:55 UTC, jeonjeunghoon commented on frontend/src/components/Category/CategorySection.tsx
> +  Section: styled.section``,
네 현재 시안상으로 아무런 디자인이 없지만 추후 디자인이 추가될것을 고려해 남겨두었는데,
styled components 대신 html element로 작성하는게 나을까요?

2023-08-01 04:55 UTC, jeonjeunghoon commented on frontend/src/hooks/useWritingsInCategory.ts
> +
맞습니다. . . 나중에 시간날 때 리팩터링 해보면 좋을 것같아요.

2023-08-01 04:57 UTC, jeonjeunghoon commented on frontend/src/hooks/useWritingsInCategory.ts
> +      : Promise.reject('No Category ID');
아 생략해도 되는군요 감사합니다!

2023-08-01 04:57 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.tsx
> +    }
네 .. 저게 안되더라구요 ㅠㅠ

2023-08-01 04:58 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.tsx
> +    }
icon에 onClick 들어갈 경우 button으로 감싸주도록 수정했습니다.

또한 공통 컴포넌트 만드는 것도 좋은 아이디어인 것같아요.

2023-08-01 05:02 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.tsx
> +        <DeleteIcon onClick={handleTrashcanIconClick} width={12} height={12} />
`openRenamingInput`, `deleteCategory` 로 명명했습니다~

2023-08-01 05:11 UTC, jeonjeunghoon commented on frontend/src/hooks/useCategoryName.ts
> +    setRename(() => '');
배칭 때문에 했었는데 고려할 필요 없을 것같아 콜백은 뺐습니다.

2023-08-01 05:20 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.tsx
> +          onKeyUp={requestChangedName}
혹시 연필 아이콘을 클릭할 때 말씀하시는건가용?

2023-08-01 05:23 UTC, nangkyeonglim commented on frontend/src/components/Category/Category.tsx
> +          onKeyUp={requestChangedName}
수정하고 있을 때 그냥 바깥쪽 아무데나 클릭해서 onBlur 될 때요!

2023-08-01 05:25 UTC, nangkyeonglim commented on frontend/src/components/Category/CategorySection.tsx
> +  Section: styled.section``,
빈 스타일은 안만들고 필요할 때 만들어도 될 거 같아요

2023-08-01 06:02 UTC, jeonjeunghoon commented on frontend/src/components/Category/Category.tsx
> +          onKeyUp={requestChangedName}
input을 닫고, 수정 사항은 반영되지 않는 방향으로 수정했습니다!

2023-08-01 08:01 UTC, jeonjeunghoon commented on frontend/src/hooks/useEraseCategory.ts
> +};
`useCategoryMutation` 이라는 훅으로 추상화해보았어요

2023-08-01 13:21 UTC, yogjin requested changes

2023-08-01 13:21 UTC, yogjin commented on frontend/src/components/Category/CategorySection/useCategoryDetails.ts
> +    };
```suggestion
    const initCategoryDetails = () => {
      return data.categories.map((category) => ({
          id: category.id,
          categoryName: category.categoryName,
          writings: null,
        };
      }));
```

2023-08-01 13:21 UTC, yogjin commented on frontend/src/components/Category/CategorySection/useCategoryDetails.ts
> +    };
return이 많아서 하나 빼봤습니다ㅎㅎ

2023-08-01 13:21 UTC, yogjin commented on frontend/src/components/Category/CategorySection/useCategoryDetails.ts
> +            };
이 객체 `updatedDetail` 인가요?
따로 선언해서 적어주면 읽기 편할 것 같아요!

2023-08-01 13:21 UTC, yogjin commented on frontend/src/components/Category/CategorySection/useCategoryDetails.ts
> +      console.log(categoryDetails);
`console.log`!

2023-08-01 13:21 UTC, yogjin commented on frontend/src/index.tsx
> +}
이 부분 현재 올라와있는 #146과 충돌날텐데, #146으로 적용해주세요!

2023-08-01 13:21 UTC, yogjin commented on frontend/src/types/apis/category.ts
> +};
파인한테도 말했지만 이 타입형식 변경을 추후에 논의해보고싶어요
```ts
export type PatchCategoryRequest = {
  categoryId: number;
} & PatchCategory;
```
다음과 같이 `PatchCategoryRequest` 만들어서 사용하는 것이 api 타입 일관성 측면에서 좋아보였기 때문입니다!

2023-08-01 13:21 UTC, yogjin commented on frontend/src/types/components/category.ts
> +};
이 친구는 왜 따로 떨어져있나요?.?

2023-08-02 01:32 UTC, jeonjeunghoon commented on frontend/src/components/Category/CategorySection/useCategoryWritings.ts
> +      return categoryId ? getWritingsInCategory(categoryId) : Promise.reject('No Category ID');
저희 로직이 카테고리 토글을 열었을 때, 선택한 카테고리의 글을 가져와야 합니다.
글을 가져오기 위해선 `선택한 categoryId`가 필요한데, 처음 Category 컴포넌트가 마운트 됐을 때엔 `선택된 categoryId` 가 없는 상태입니다.
저희가 사용하는 `useGetQuery` 는 사용할 때 fetch를 바로 실행하는데 `categoryId` 가 없기 때문에 `getWritingsInCategory` 를 사용할 수 없습니다.
지금 작성하면서 깨달았는데, reject를 반환하는 로직을 `getWritingsInCategory` 내부에서 수행해도 되겠다는 생각을 하게 됐네요

2023-08-02 01:35 UTC, jeonjeunghoon commented on frontend/src/components/Category/CategorySection/useCategoryWritings.ts
> +  const [categoryId, setCategoryId] = useState<number | null>(null);
위에 작성한 것처럼 `getWritingsInCategory` 내부에 reject로직이 있으면 외부에 선언해도 될 것같아요

2023-08-02 01:47 UTC, jeonjeunghoon commented on frontend/src/components/Category/CategorySection/CategorySection.tsx
> +  };
네 좋아요~!

2023-08-02 01:47 UTC, jeonjeunghoon commented on frontend/src/components/Category/CategorySection/useCategoryDetails.ts
> +    };
훨씬 간결해졌네요~!

2023-08-02 01:52 UTC, jeonjeunghoon commented on frontend/src/components/Category/CategorySection/useCategoryDetails.ts
> +            };
추가된 카테고리 데이터 `addedCategory` 입니다.
따로 선언을 안하니 확실히 코드를 읽기에 혼동이 오네요 ....
말씀하신대로 따로 선언 추가했습니다~

2023-08-02 01:52 UTC, jeonjeunghoon commented on frontend/src/index.tsx
> +}
넵!

2023-08-02 01:56 UTC, jeonjeunghoon commented on frontend/src/types/apis/category.ts
> +};
이후에 리팩터링 하면 좋을 것같아요!

2023-08-02 02:20 UTC, jeonjeunghoon commented on frontend/src/types/components/category.ts
> +};
이 친구는 `useCategoryDetails` 에서 사용되는 타입인데, 현재 `writings` 타입 폴더에 따로 선언되어 있는게 없고, 해당 타입을 추가하면 다른 타입들도 수정해야할 것같아서 일단 따로 떨어뜨려 놨습니다.

또한 `Writing` -> `CategoryWriting` 으로 이름을 구체화했습니다.

2023-08-02 02:24 UTC, jeonjeunghoon commented on frontend/src/constants/apis/url.ts
> +export const categoryURL = `categories`;
넵 추가했습니다~

2023-08-02 02:25 UTC, jeonjeunghoon commented on frontend/src/components/Category/CategorySection.tsx
> +  Section: styled.section``,
Section에 따로 width 가 필요해서 사용하게 됐습니다~

2023-08-02 03:08 UTC, nangkyeonglim approved these changes

2023-08-02 03:08 UTC, nangkyeonglim commented on frontend/src/constants/apis/url.ts
> +export const categoryURL = `${baseURL}categories`;
이거 `/` 없애면 에러안나나요?

2023-08-02 04:37 UTC, jeonjeunghoon commented on frontend/src/constants/apis/url.ts
> +export const categoryURL = `${baseURL}categories`;
아이고 저게 왜 없지 다시 추가하겠습니다

2023-08-02 05:45 UTC, yogjin approved these changes
긴 시간이었네요! 수고하셨습니다~

2023-08-02 05:51 UTC, merged