[FE] OAUTH 로그인 기능 구현
woowacourse-teams/2023-dong-gle pull request #233
Opened 2023-08-10 11:07 UTC by jeonjeunghoon

### 🛠️ Issue

- close #229 

### ✅ Tasks
- [x] Kakao 컴포넌트 구현
- [x] OauthPage 컴포넌트 구현

### ⏰ Time Difference
- 4 -> 4

### 📝 Note

- 현재 `Kakao` 컴포넌트에서 `get` 요청 시 cors 에러가 발생하는 이슈가 있습니다. 그래서 `redirectToKakao` 라는 이벤트 핸들러에서 직접 리다이렉션을 진행합니다. 백엔드분들과 함께 작업을 해봐야할 것같습니다.
- Oauth 플랫폼이 추가되면 Kakao 컴포넌트를 추상화 할 수 있을 것같습니다. 그래서 우선 Kakao 컴포넌트를 제외한 다른 로직들은 추상화를 해보았습니다.
- 현재 OauthPage에서의 `post` 요청 시 500에러가 발생합니다. 그래서 확인 가능한 동작은 카카오 버튼 클릭 -> 로그인 페이지 이동 -> 500 에러 입니다.

<img width="1680" alt="스크린샷 2023-08-10 오후 7 48 13" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/8aacba27-fbc3-427d-8640-1c128a4f4a6f">
<img width="1680" alt="스크린샷 2023-08-10 오후 7 48 16" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/085d6953-d95f-4b21-b681-db4009d38278">
<img width="1703" alt="스크린샷 2023-08-10 오후 7 48 21" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/c79b9c0b-06b8-44c3-b6b4-062dc43960e5">

2023-08-10 15:42 UTC, nangkyeonglim requested changes

2023-08-10 15:42 UTC, nangkyeonglim commented on frontend/src/apis/login.ts
> +    },
이거 이제 추상화 될 때 들어가서 없어도 될 것 같습니다!

2023-08-10 15:55 UTC, jeonjeunghoon commented on frontend/src/pages/Layout/Layout.tsx
> +      <Kakao />
그게 낫겠네요~!

2023-08-10 15:58 UTC, jeonjeunghoon commented on frontend/src/routes/Router.tsx
>        ],
App > IntroducePage > OauthPage > 동글페이지 > Layout > Outlet
제가 이해하기론 이렇게인데 맞나요?

2023-08-10 15:58 UTC, jeonjeunghoon commented on frontend/src/apis/login.ts
> +    },
수정했습니다~

2023-08-10 16:04 UTC, jeonjeunghoon commented on frontend/src/components/Login/Kakao.tsx
> +    window.location.href = oauthRedirectURL('kakao');
원래 백엔드에서 `http://3.35.7.85/api/oauth/login/kako?redirect_uri=http://localhost:3000/oauth/kakao` 주소(개발 서버 기준)로 클라이언트를 리다이렉션 시켜줘야 하는데 cors 에러 때문에 백엔드에서 리다이렉션이 안되는 상황이에여

그래서 클라이언트에서 window.location.href 로 리다이렉션 시키게 됐습니다

2023-08-12 08:49 UTC, jeonjeunghoon commented on frontend/src/constants/apis/url.ts
> +const redirectURL = (platform: OauthPlatform) => `https://donggle.blog/oauth/${platform}`; // 프로덕션 서버용
env 파일에 환경에 따라 domain 주소가 바뀌게 설정해뒀습니다

2023-08-12 13:46 UTC, nangkyeonglim commented on frontend/src/constants/apis/url.ts
> +const redirectURL = (platform: OauthPlatform) => `https://donggle.blog/oauth/${platform}`; // 프로덕션 서버용
env 파일 단톡방에 공유좀 해주실 수 있나요?

2023-08-12 14:04 UTC, nangkyeonglim commented on frontend/src/routes/Router.tsx
>        ],
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/fb0b3815-9d9e-405f-8d64-2ae1a7ae9b23)

지금 당장은 App.tsx에서 <Layout />을 <Outlet />으로 변경하고 이런 식으로 중첩 라우터로 구성할 수 있을 것 같아요!

* 소개 페이지
* 로그인 페이지 - 카카오 로그인, 구글 로그인 페이지 등
* 스페이스 페이지(가명) - 글 목록 페이지, 글 페이지 등

2023-08-12 14:07 UTC, nangkyeonglim requested changes

2023-08-12 14:07 UTC, nangkyeonglim commented on frontend/src/pages/OauthPage/OauthPage.tsx
> +        code: searchParams.get('code') ?? '',
나중에 error일 때는 params에 code가 아닌 error와 error_description이 오는데 이에 대한 처리도 해줘야할 것 같네요
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/d733ef69-3e63-468c-8ba7-4bb98b911fc5)

2023-08-13 08:38 UTC, jeonjeunghoon commented on frontend/src/routes/Router.tsx
>        ],
오 이 구조 좋아보이네요

2023-08-13 08:39 UTC, jeonjeunghoon commented on frontend/src/components/Login/Kakao.tsx
> +    window.location.href = oauthRedirectURL('kakao');
네넵 cors 때문에 프론트에서 하고 있습니다

2023-08-13 08:54 UTC, jeonjeunghoon commented on frontend/src/pages/OauthPage/OauthPage.tsx
> +        code: searchParams.get('code') ?? '',
오... 확인해보니 그렇네요.
에러가 발생할 땐 `code` 대신 `error` 와 `error_description` 이 오네용
근데 저희 API 명세에는 `{ code: "", redirect_uri: "" }` 요청만 정의되어 있어서 이 부분은 백엔드 분들에게 여쭤보아야 할 것같네요~

2023-08-13 13:10 UTC, nangkyeonglim approved these changes
라우터 구조만 코멘트대로 수정하면 될 것 같아요! 고생하셨습니다~

2023-08-14 02:30 UTC, yogjin approved these changes
수고하셨습니다
어렵네요..
코멘트 몇 자 남겨두었습니다.

2023-08-14 02:30 UTC, yogjin commented on frontend/src/components/Login/Kakao.tsx
> +  // const redirect = () => refetch();
주석 남겨둔 이유가 있을까요?

2023-08-14 02:30 UTC, yogjin commented on frontend/src/components/Login/Kakao.tsx
> +const Kakao = () => {
`KakaoLoginButton` 같은 네이밍은 어떨까요?
그냥 `Kakao` 라서 어떤 컴포넌트인지 예상이 잘 안가네요

2023-08-14 04:15 UTC, jeonjeunghoon commented on frontend/src/components/Login/Kakao.tsx
> +  // const redirect = () => refetch();
현재 API 명세에 있지만 사용은 안하고 있어서 지울 수는 있는데 ... cors 에러가 해결되면 사용할 수 있어서 혹시 몰라 남겨뒀습니다.

2023-08-14 04:20 UTC, jeonjeunghoon commented on frontend/src/components/Login/Kakao.tsx
> +const Kakao = () => {
피드백 주신대로 수정했습니다!

2023-08-14 04:20 UTC, jeonjeunghoon commented on frontend/src/components/Login/Kakao.tsx
> +  // const redirect = () => refetch();
그래도 일단 사용은 안하니 삭제했습니다!

2023-08-14 04:24 UTC, merged