[FE] feat: 글 삭제 기능 구현
woowacourse-teams/2023-dong-gle pull request #245
Opened 2023-08-11 05:30 UTC by jeonjeunghoon

### 🛠️ Issue

- close #241 

### ✅ Tasks
- [x] 글 삭제 요청 로직 작성
- [x] 글 삭제 컴포넌트 구현
- [x] 글 삭제 요청 msw mocking
- [x] 카테고리에 글 삭제 컴포넌트 붙이기

### ⏰ Time Difference
- 2 -> 1

### 📝 Note
- 디자인에 일관성이 없어서 나중에 전체적으로 디자인을 맞춰야할 것같아요. 현재 휴지통 컴포넌트가 호버 상태일 때, 백그라운드 컬러가 gray6 인데, 다른 아이콘에선 gray5입니다. gray6으로 한 이유는, 글 컴포넌트가 호버 상태일 때 백그라운드 컬러가 gray5라서 그렇습니다. 글 컴포넌트의 호버 백그라운드 컬러를 gray4로 해보았지만, 색이 너무 연해서 가시성이 떨어질 것같아 이렇게 처리했습니다.

![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/638943a5-58c0-4faa-85db-3f47fb845689)

2023-08-11 05:49 UTC, nangkyeonglim requested changes
코멘트 확인해주세요!

2023-08-11 05:49 UTC, nangkyeonglim commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +  };
이거 사용하려다가 만 것인가요? 지금 이벤트 버블링 일어나고 있는 것 같아요..!

2023-08-11 05:49 UTC, nangkyeonglim commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +  };
+ onClick 할 때 정말 삭제할 것인지 confirm 창이라도 띄우는 게 좋을 것 같아요

2023-08-11 05:49 UTC, nangkyeonglim commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +            <DeleteButton onClick={() => mutate([categoryId])} />
이거 writingId가 아니라 categoryId가 들어가고 있는데요?!

2023-08-11 06:15 UTC, jeonjeunghoon commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +            <DeleteButton onClick={() => mutate([categoryId])} />
아앗........................>>? 그렇네요 감사함다!!!

2023-08-11 06:56 UTC, jeonjeunghoon commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +  };
버블링은 안일어나고 있어요! 그 이유가 `stopPropagation()` 을 걸어도 동일한 요청이 가는걸 확인했어요.
그리고 `confirm` 추가했습니다~!

2023-08-11 12:29 UTC, yogjin requested changes
서버 api가 완성되지 않아 결과물을 볼 수 없는게 아쉽네요.
msw를 잘 이용하려면 글 목록과 카테고리 배열을 런타임때 만들어 놓고 
각 메서드 핸들러에 대해 실제 동작을 흉내내어(배열의 값을 CRUD) 렌더링 변화를 직접 확인할 수 있게 하면 좋을 것 같습니다.
이건 다같이 한번 얘기해보시죠~

2023-08-11 12:29 UTC, yogjin commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +
다른 컴포넌트에 분리한 mutation 훅 참고해서 훅 으로 분리해도 좋을 것 같아요.

2023-08-11 12:29 UTC, yogjin commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +    flex: 1;
flex는 왜 추가했는지 궁금합니다

2023-08-11 12:29 UTC, yogjin commented on frontend/src/mocks/handlers/trash.ts
> +];
조금 허전한 감이 있네요🤔

2023-08-12 16:41 UTC, jeonjeunghoon commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +
`useDeleteWritings` 훅으로 분리해봤습니다~!

2023-08-12 16:44 UTC, jeonjeunghoon commented on frontend/src/components/Category/WritingList/WritingList.tsx
> +    flex: 1;
글 제목이 길어질 때 아이콘이 사라질 것같아 추가했습니다.
근데 `flex: 1` 을 지워보니 아이콘이 그대로 남아있네요 ㅎㅎ...
그래서 지웠습니다~

2023-08-12 16:45 UTC, jeonjeunghoon commented on frontend/src/mocks/handlers/trash.ts
> +];
이 부분은 위에서 말씀하신대로 각 핸들러들의 행동을 흉내내보는게 좋을 것같네요!

2023-08-13 10:56 UTC, nangkyeonglim approved these changes
확인했습니다~!

2023-08-13 11:52 UTC, yogjin approved these changes
확인했습니다~

2023-08-13 12:03 UTC, merged