[FE] feat: 휴지통 기능 구현
woowacourse-teams/2023-dong-gle pull request #281
Opened 2023-08-15 09:19 UTC by jeonjeunghoon

### 🛠️ Issue

- close #248 

### ✅ Tasks
- [x] TrashCan 컴포넌트 구현
- [x] TrashCanTable 컴포넌트 구현
- [x] TrashCanPage 페이지 구현
- [x] trash 관련 api 요청 로직 구현
- [x] trash api 관련 핸들러 작성

### ⏰ Time Difference
- 1 -> 6

### 📝 Note
- 현재 WritingList 컴포넌트와 DeletedWritingList 컴포넌트를 추상화하고 싶은데, `categoryId` WritingList에서 Props로 사용하는 categoryId 가 애매해서 추상화하지 못하고 있습니다. API 명세가 바뀌면 그때 할 수 있을 것같아요.
- mocking으로 요청이 잘 되는 것을 확인했습니다. 그러나 현재 계정이 없고 서버와 통신이 되지 않는 상황입니다.

2023-08-15 13:40 UTC, nangkyeonglim requested changes
고생하셨어요! 코멘트 확인만 해주세요~!

2023-08-15 13:40 UTC, nangkyeonglim commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
> +    min-width: 0;
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/1fb2e044-604a-45a1-a0f2-f98374e166a5)

![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/0004f326-b501-452e-8e8d-7f0836ab1518)

이거 hover시에 background-color 영역이 달라지는 거 같아서 여기서 width: 100% 줘야할 것 같아요!

2023-08-15 13:40 UTC, nangkyeonglim commented on frontend/src/components/TrashCanTable/useRestoreDeletedWritings.ts
> +    onError: () => alert('글 삭제가 실패했습니다.'),
이거 글 복구가 실패했습니다로 고쳐야할 것 같아요!

2023-08-16 02:01 UTC, jeonjeunghoon commented on frontend/src/pages/TrashCanPage/TrashCanPage.tsx
> +  if (isLoading) return <>로딩 중...</>;
넵 좋아요~! 제가 지금은 suspense에 대한 이해도가 낮아서 이후에 리팩터링하겠습니다~

2023-08-16 02:01 UTC, jeonjeunghoon commented on frontend/src/components/TrashCanTable/useRestoreDeletedWritings.ts
> +    onError: () => alert('글 삭제가 실패했습니다.'),
앗 감사합니다!

2023-08-16 05:32 UTC, jeonjeunghoon commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
> +    min-width: 0;
휴지통 수정하면서 카테고리도 전체적으로 디자인 살짝 수정했습니다~!

2023-08-16 07:41 UTC, nangkyeonglim commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
> +    min-width: 0;
좋습니다~!

2023-08-16 07:41 UTC, nangkyeonglim approved these changes

2023-08-16 12:10 UTC, yogjin approved these changes
수고하셨습니다~

2023-08-16 12:10 UTC, yogjin commented on frontend/src/hooks/useDeletedWritings.ts
> +    {
`useQuery` 의 `onError` 가 deprecated 된다고 하네요. 
지금은 alert을 띄워주기 위해 사용했지만, ErrorBoundary에 위임하거나, isError로 조건부 렌더링을 하여 refetch 버튼을 렌더링해주는 것도 방법이 될 것 같습니다!

2023-08-16 12:12 UTC, jeonjeunghoon commented on frontend/src/hooks/useDeletedWritings.ts
> +    {
아 좋습니다~!

2023-08-16 12:12 UTC, merged