[FE] feat: 전역 상태(현재 보고있는 글, 카테고리) 추가
woowacourse-teams/2023-dong-gle pull request #364
Opened 2023-09-04 03:40 UTC by yogjin

### 🛠️ Issue

- close #363 

### ✅ Tasks
- [전역상태 라이브러리](https://github.com/yogjin/react-global-state) 도입 

### ⏰ Time Difference
- 

### 📝 Note
-

2023-09-05 12:28 UTC, jeonjeunghoon reviewed
코멘트로 궁금한 점 남겨뒀어요!

2023-09-05 12:28 UTC, jeonjeunghoon commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +  if (!writingId) return <div>존재하지 않는 글입니다.</div>;
`writingId` 가 `false` 일 경우가 있나요?

2023-09-05 12:28 UTC, jeonjeunghoon commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    setActiveWritingInfo?.(writingId ? { id: writingId, isDeleted: isDeletedWriting } : null);
`setActiveWritingInfo` 에 옵셔널 체이닝을 사용해야 하는 이유가 궁금해요

2023-09-05 12:28 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +  if (!activeCategoryId) return <div>카테고리가 존재하지 않습니다.</div>;
여기도 `WritingPage` 와 마찬가지로 `activeCategoryId` 가 `false` 값으로 평가될 수 있나요?

2023-09-05 12:28 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
>  };
jsx 구문이 `data` 선언문으로 분리되어서 조금은 어색하게 느껴져요
`activeCategoryId` 가 `falsy` 값일 경우 때문에 그런건가요?

2023-09-05 18:25 UTC, yogjin commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +  if (!writingId) return <div>존재하지 않는 글입니다.</div>;
`writingId` 가 `undefined` 일수도 있어서 일종의 타입가드로써 조건부 렌더링을 했습니다만..
이제 생각해보니 존재하는 글과 카테고리를 클릭했는데 개발자의 실수로 `<div>존재하지 않는 글입니다.</div>` 이 보여지면 유저 입장에서는 당혹스럽겠네요. 
또 에러 추적도 힘들 것 같구요.
`activeWritingInfo`에 접근하는 로직을 훅으로 빼서 값이 `undefined`인 경우 훅 내부에서 throw Error를 하고, 반환하는 값의 타입은 nullable 하도록 만들어보겠습니다.

2023-09-05 18:25 UTC, yogjin commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
>  };
질문 이해를 못했습니다..
더 자세하게 설명부탁드려요

2023-09-05 18:27 UTC, yogjin commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    setActiveWritingInfo?.(writingId ? { id: writingId, isDeleted: isDeletedWriting } : null);
`activeWritingInfo`가 `undefined` 일 수도 있어서 그렇습니다.
훅을 만들어서 해결가능할 것으로 보입니다.

2023-09-06 02:17 UTC, nangkyeonglim commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +      <WritingTable categoryId={activeCategoryId} writings={data?.writings ?? []} />
카테고리에 글 없을 경우 이렇게 나오는데
<img width="953" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/0a794a3a-8c66-429e-aa7a-1e374339f473">

뭔가 이렇게 안내 해주는 게 좋을 것 같아욥
```suggestion
      { 
      data?.writings ? 
        <WritingTable categoryId={activeCategoryId} writings={data?.writings} /> 
        : <p> 카테고리 내 글이 존재하지 않습니다 </p> 
      }
```

2023-09-07 07:47 UTC, jeonjeunghoon commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +  if (!writingId) return <div>존재하지 않는 글입니다.</div>;
아하 undefined일 경우가 있어서 그렇군요~!
훅으로 관심사 분리하여 데이터를 사용하는 것에만 관심을 두게 만들면 좋을 것같아요! 근데 nullable 한게 어떤 의미인지 모르겠어용

2023-09-07 07:48 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +  if (!activeCategoryId) return <div>카테고리가 존재하지 않습니다.</div>;
이것도 마찬가지로 `undefined` 일 가능성이 있어서 그런거죠?

2023-09-07 07:48 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
>  };
파인 말이 맞아요!

2023-09-07 07:49 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
>  };
이 부분도 위에서 말씀하신 것처럼 typeguard 하는 부분을 제거하면 해결될 문제같아요~

2023-09-16 18:43 UTC, yogjin commented
커밋 추가했습니다!
-  카테고리, 휴지통 클릭 로딩 스피너 추가, 카테고리가 비었을 시 메시지 추가
- 전역 상태 `activeCategoryId`, `activeWritingInfo` set은 navigate 하는 `go~` 메서드 내부가 아닌 `Page` 내부에서 수행합니다!
  - `go~` 내부에서 navigate할 때 state를 함께 넘겨줍니다. (기존 로직으로 복귀)
  - 새로고침 시 초기화된 상태를 다시 set하여 현재 보고있는 글을 그대로 볼 수 있습니다.
  - strictmode에서 useEffect 가 두 번 실행되어 동작에 문제가 있던 부분도 해결했습니다.
- 현재 url을 임의로 수정할 시 여전히 에러페이지가 뜨는데, 이 부분은 추후 에러바운더리 도입 시 함께 해결하면 좋을 듯 합니다.

2023-09-18 07:40 UTC, nangkyeonglim requested changes
로컬 스토리지 비우고 한번 더 테스트 후에 리뷰요청 주실 수 있나요?
현재 에러때문에 볼 수가 없네요😿

2023-09-18 07:53 UTC, nangkyeonglim commented on frontend/src/components/FileUploadModal/FileUploadModal.tsx
> +    useFileUploadModal({ closeModal, categoryId: activeCategoryId });
이 부분에서 현재 에러가 터지고 있었네요.
기존에는 categoryId가 없으면 defaultCategoryId를 넣어줬는데 null 때문에 터지고 있는 거 같아요ㅜ

2023-09-18 08:46 UTC, yogjin commented on frontend/src/components/Category/List/useCategories.ts
> +    setActiveCategoryIdState(data.categories[0].id);
`useCategories`에 카테고리 받아오면 `localStorage`에 `defaultCategoryId` set하는 로직 추가했습니다!

2023-09-18 08:47 UTC, yogjin commented on frontend/src/components/FileUploadModal/FileUploadModal.tsx
> +    useFileUploadModal({ closeModal, categoryId: activeCategoryId });
null 타입 가드 처리를 위해 만들었던 `useActiveCategoryId` 훅을 제거했습니다. 대신 [6ca95fb](https://github.com/woowacourse-teams/2023-dong-gle/pull/364/commits/6ca95fbfdfd80f00f6f031aa764f0cea99e5ee1e)와 같이 수정했습니다.

2023-09-19 02:13 UTC, nangkyeonglim requested changes
activeCategoryId 쪽만 다시 확인해주세요!

2023-09-19 02:13 UTC, nangkyeonglim commented on frontend/src/components/Category/List/useCategories.ts
> +    setActiveCategoryIdState(data.categories[0].id);
처음에 activeCategoryIdState를 기본 카테고리 id로 초기화해주는 이유가 있나요?

2023-09-19 02:13 UTC, nangkyeonglim commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +    return () => setActiveCategoryId(Number(localStorage.getItem('defaultCategoryId')));
writingPage는 null로 초기화해주는데 writingTablePage는 기본카테고리로 초기화하는 이유가 있을까요?

2023-09-19 02:13 UTC, nangkyeonglim commented on frontend/src/globalState/index.ts
> +  Number(localStorage.getItem('defaultCategoryId')),
activeCategoryIdState가 null인 경우가 현재 코드에서 없는거같아요..!
그리고 localStorage에 defaultCategoryId가 없으면 Number(null) => 0으로 초기화 될 거 같은데 null로 초기화 시키는 게 어떤가요

2023-09-19 05:26 UTC, jeonjeunghoon requested changes
궁금한 점 코멘트 남겼습니다!
고생 많으셨어요 😊

2023-09-19 05:26 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +    return () => setActiveCategoryId(Number(localStorage.getItem('defaultCategoryId')));
해당 부분도 `null` 로 초기화해도 동작에 변함이 없어요!

2023-09-20 02:00 UTC, yogjin commented on frontend/src/components/Category/List/useCategories.ts
> +    setActiveCategoryIdState(data.categories[0].id);
`activeCategoryId`는 가져오기 한 글이 담길 카테고리를 정할 때 이용하는 식별자라서, 로그인 직후 카테고리 목록을 받아올 때 기본 카테고리 id를 `activeCategoryId`로 초기화하고 있습니다.

2023-09-20 02:01 UTC, yogjin commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +    return () => setActiveCategoryId(Number(localStorage.getItem('defaultCategoryId')));
`fileUploadModal`에서 `localStorage.getItem('defaultCategoryId')`를 사용하는 로직을 없앴기 때문에, 클린업에서 초기화해주어야 합니다

2023-09-20 02:09 UTC, yogjin commented on frontend/src/globalState/index.ts
> +  Number(localStorage.getItem('defaultCategoryId')),
`-1`로 초기화 하였습니다!
`useCategories` 에서 defaultCategoryId를 가져와서 set 하기 때문에 이때 에러터지면 ErrorBoundary에서 잡힙니다.
따라서 개발할 때 편하도록(activeCategoryIdState를 갖다 쓰는 쪽에서 매번 null 체크 안해도 되도록) activeCategoryIdState에 null을 사용하지 않고 -1로 초기화 했습니다.

2023-09-20 02:11 UTC, yogjin commented on frontend/src/components/Category/List/useCategories.ts
> +    setActiveCategoryIdState(data.categories[0].id);
```ts
const defaultCategoryId = data.categories[0].id;

localStorage.setItem('defaultCategoryId', String(defaultCategoryId));
setActiveCategoryIdState(defaultCategoryId);
```
이렇게 그냥 상수로 따로 선언했습니다!

2023-09-20 02:12 UTC, yogjin commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
>              <S.Text>{deletedWriting.title}</S.Text>
반영했습니다

2023-09-20 02:16 UTC, yogjin commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +      setActiveCategoryId(Number(localStorage.getItem('defaultCategoryId')));
https://github.com/woowacourse-teams/2023-dong-gle/pull/364#discussion_r1330869846 와 https://github.com/woowacourse-teams/2023-dong-gle/pull/364#discussion_r1330870533 로 답변할 수 있을 것 같습니다.

2023-09-20 02:23 UTC, yogjin commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
>    if (!deletedWritings || deletedWritings?.length === 0)
좋아요 반영했습니다

2023-09-20 03:53 UTC, yogjin commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +  }, [activeCategoryId]);
좋습니다~ 실험적으로 한글 변수명을 이용해봤습니다.

2023-09-20 08:32 UTC, nangkyeonglim approved these changes
고생하셨습니다~!

2023-09-20 08:56 UTC, jeonjeunghoon commented on frontend/src/components/Category/List/useCategories.ts
> +    setActiveCategoryIdState(data.categories[0].id);
아하 로그인 직후 `activeCategoryId` 는 `null` 인가 보군요!

2023-09-20 08:57 UTC, jeonjeunghoon commented on frontend/src/pages/WritingTablePage/WritingTablePage.tsx
> +  }, [activeCategoryId]);
오 ......

2023-09-20 09:02 UTC, jeonjeunghoon approved these changes
한글 파일과 한글 코드가 굉장히 인상적이군요...
확실히 잘 읽히는 것같아요
저도 어려운 로직이 있는 코드에는 도입을 검토해봐야겠어요

긴 시간 고생 많으셨어요!

2023-09-21 08:43 UTC, merged