[BE] Feat: 로그인 기능 추상화 및 동시성 문제
woowacourse-teams/2023-dong-gle pull request #371
Opened 2023-09-05 08:26 UTC by ingpyo

### 🛠️ Issue

- close #367 

### ✅ Tasks
- 로그인이 추가될 때 중복되는 코드 제거 및 앞으로의 확장성 목적의 추상화
- dev환경에서 회원가입 시 요청을 2번씩 보내는데 이 경우 회원의 정보가 2번 저장되는 에러 동시성 문제 처리

### ⏰ Time Difference
- 2

2023-09-06 04:56 UTC, HubCreator approved these changes
비버! 코드 잘 봤습니다! 복잡했을텐데 호딱 해주셨네요 ㅎㅎㅎ 고생 많으셨습니다!!

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/domain/member/Member.java
> +    @Column(name = "SOCIAL_ID_UNIQUE", unique = true)
`@Table` 쪽에 uniqueContraints 제약 조건 걸어줬는데, `@Column`에서 unique 속성도 같이 있네요! `@Column`의 속성을 지워도 잘 동작하는지 궁금합니다!

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/domain/member/Member.java
>      }
socialId는 Kakao로부터 받은 id를 받는 전용 컬럼이라고 생각하면 되나요?! 
만약 추후에 Google이나 Github로부터 로그인 id를 가져와서 저장하는 상황에서 socialId 변수에 값을 저장하도록 한다면 조금 더 유연하게 createByKakao보다는 create나 createWithSocialId정도로 해도 좋을 것 같은데 어떻게 생각하시나요?!

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/SocialType.java
> +                .orElseThrow(() -> new IllegalArgumentException("일치하는 소셜 타임이 없습니다."));
소셜 타임 -> 소셜 타입!!

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/SocialType.java
> +}
전체적으로 파일 끝 개행 한 번만 확인해주세요 ㅎㅎㅎ

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/OauthClients.java
> +    }
뭔가 반환한다라는 뜻을 가진 메서드 네이밍은 어떨까요!? getXX 혹은 findXX 를 붙여도 좋을 것 같아요

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/AuthService.java
> +    }
DB 관련 로직이 없어서 `@Transactional(readOnly = true)`를 붙이면 어떨까요!?!?

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/ui/AuthController.java
> +        final TokenResponse response = authService.login(socialType, oAuthAccessTokenRequest);
클라이언트에서 소셜 타입을 주는 것으로 수정되었군요!! 깔끔합니다

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/AuthService.java
>      }
이렇게 방어로직이 추가되었군요! 멋집니다 ㅎㅎㅎ

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/AuthService.java
>      }
이부분은 비버가 현재 작성해주신대로 `@Transactional(readOnly = true)`를 붙이면 안되겠네요ㅎㅎ initializeMember에서 member를 찾지 못했을 때 영속화시키는 로직이 있어 안될 것 같습니다. 정상적인 로그인이라면 조회 작업만 할텐데, 예외 케이스의 경우에서 삽입 작업을 진행하고 있어서 문제가 되네요. 이를 (내부 호출 문제를 유의해서)분리할 수는 있겠는데 현재 상황에서는 굳이 분리해야 할 때인가 싶긴 합니다. (그냥 이런 생각이 들어서 코멘트 남겼습니다 굳굳)

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/service/oauth/kakao/KakaoOauth2Client.java
> +    }
`@RequiredArgsConstructor` 애너테이션을 사용할 수 있을 것 같네요! 

추상화가 잘 된 것 같아요! 또한 기존의 코드보다 더 객체지향적인 것 같습니다. 클래스를 쪼개서 메시지를 보내는게 인상깊네요ㅎㅎ

2023-09-06 04:56 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/config/VendorConfiguration.java
> +    public OauthClients oAuth2Clients(final Set<OauthClient> clients) {
`OauthClient` 인터페이스를 구현한 클래스를 빈으로 등록해준다! 멋있네요 ㅎㅎㅎㅎ

2023-09-06 07:37 UTC, echo724 requested changes

2023-09-07 07:24 UTC, echo724 requested changes

2023-09-07 07:24 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/exception/business/JoinDuplicateException.java
> +public class JoinDuplicateException extends BusinessException {
비지니스 예외인데 이름이 추상적인거 같습니다. MemberAlreadyExistsException이나 DuplicatedMemberException 등의 이름은 어떨까요?

2023-09-07 07:24 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/config/VendorConfiguration.java
> +    public LoginClients loginClients(final Set<LoginClient> clients) {
Awesome!!

2023-09-07 07:24 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/ui/AuthController.java
> +    @GetMapping("/login/{socialType}/redirect")
프론트 PR이 준비되어야겠군요 ㅜㅜ

2023-09-12 05:20 UTC, echo724 approved these changes

2023-09-12 05:20 UTC, ezzanzzan approved these changes
최고 👍

2023-09-12 05:43 UTC, merged