[BE] Feat 블로그 기능 추상화
woowacourse-teams/2023-dong-gle pull request #376
Opened 2023-09-06 08:14 UTC by ingpyo

### 🛠️ Issue

- close #373 
### ✅ Tasks
- 블로그가 추가될 때 중복되는 코드 제거 및 앞으로의 확장성 목적의 추상화

### ⏰ Time Difference
- 3

2023-09-11 08:29 UTC, echo724 requested changes
Bean 주입을 통한 추상화 멋지네요! 몇몇 부분만 수정 부탁해요!

2023-09-11 08:29 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/service/vendor/medium/MediumApiClient.java
> +                .block().data().toPublishResponse();
오 DTO도 추상화 좋아요

2023-09-11 08:29 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/service/BlogClients.java
> +            final List<String> tags,
나머지 파라미터들을 묶어서 PublishRequest DTO를 만들어도 좋을 것 같습니다. 어차피 같이 publish 메서드 안에서 사용되기 때문에 묶어도 괜찮을꺼 같아요!

2023-09-11 08:29 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/PublishResponse.java
> +        LocalDateTime bateTime,
허허 dateTime 고고

2023-09-11 08:29 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/domain/blog/BlogType.java
> +                .orElseThrow(() -> new IllegalArgumentException("토큰 타입 못찾음"));
존댓말 써주세요.. ㅋㅋ

2023-09-11 08:29 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/domain/member/MemberCredentials.java
>          return Optional.ofNullable(tistoryToken);
이 메서드 아래 메서드랑 중복인거 같아요!

2023-09-12 05:44 UTC, ezzanzzan approved these changes

2023-09-12 06:21 UTC, HubCreator approved these changes
고생하셨습니다

2023-09-12 06:22 UTC, merged