[FE] refactor: highlight.js 대신 prismjs를 이용해 번들 사이즈 최적화
woowacourse-teams/2023-dong-gle pull request #394
Opened 2023-09-11 12:13 UTC by yogjin

### 🛠️ Issue

- close #383

### ✅ Tasks
- 가벼운 `prismjs` 설치 
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/5fdbaf95-aa27-4608-9992-ce2af3518c1c)

`highlight.js`는 모든 언어를 import해서 하이라이팅을 적용한다. (모든 js 파일 요청)
반면에 `prismjs`는 하이라이팅이 필요한 언어의 prism을 import해서 적용한다. (필요한 js파일 요청)

- 동적 import 적용하여 요청 최적화 
  - 백엔드에서 받아온 글의 html string을 파싱('code[class^="language-"]')하여 코드블럭으로 이용하고있는 언어들의 prism을 동적으로 import 한다.

### ⏰ Time Difference
- 6 + 0

### 📝 Note
- 적용한 `prismjs` 스타일이 노션이랑 같아서 이쁘네요

2023-09-12 04:44 UTC, jeonjeunghoon reviewed
코멘트 남겼어요 고생하셨습니다~

2023-09-12 04:44 UTC, jeonjeunghoon commented on frontend/src/hooks/@common/useCodeHighlight.ts
> +};
useCondeHighlight의 동작에 대해 간단히 설명해주실 수 있나요?

2023-09-12 05:13 UTC, nangkyeonglim requested changes
좋습니다!
highlight.js도 필요한 언어를 import해서 하이라이팅을 적용해 볼 수는 없을까요?

2023-09-12 05:13 UTC, nangkyeonglim commented on frontend/src/hooks/@common/useCodeHighlight.ts
> +        .filter(Boolean);
이거 맞는 지 모르겠는는데 이런식으로 써볼 수 있을 것 같아요!

```suggestion
      const languages = Array.from(codeElements)
      .filter((element) => {
           return element.className.includes(/language-(\w+)/);                                           
      }).map(match => match[1])
```

2023-09-12 08:49 UTC, yogjin commented on frontend/src/components/WritingViewer/WritingViewer.tsx
> +      background-color: transparent;
`code` 태그의 `background-color`이 `gray2`로 되어있어서 배경색이 보이더라구요
<img width="553" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/55f446e4-8689-4af6-9bb5-fb815a200755">
투명으로 하기 전에는 코드블럭 내부 코드 배경색이 위 빨간 박스의 배경색으로 보였습니다!
참고로 빨간 블럭들의 배경은 잘못된게 아니라 의도된 스타일입니다(노션도 같은 스타일을 사용하고 있어요)

2023-09-12 09:27 UTC, yogjin commented on frontend/src/hooks/@common/useCodeHighlight.ts
> +        .filter(Boolean);
dom파싱 부분 없애고 [eadacf9](https://github.com/woowacourse-teams/2023-dong-gle/pull/394/commits/eadacf9a31bdfa73323ff7d90265d6f5d38e5329) 로 수정했습니다.

2023-09-12 09:32 UTC, yogjin commented on frontend/src/hooks/@common/useCodeHighlight.ts
> +};
로직을 수정했습니다! dom파싱 부분 없애고 [eadacf9](https://github.com/woowacourse-teams/2023-dong-gle/pull/394/commits/eadacf9a31bdfa73323ff7d90265d6f5d38e5329) 로 수정했습니다.

## 동작설명
`importPrism` 

1. 서버에서 받은 html string 받음 -> 2. 정규표현식(`<code class="language-(\w+)">`)를 이용해 코드블럭이 이용하는 언어들 배열 얻기 -> 3. 언어 배열에 있는 언어들의 prism 모듈 동적 import

`Prism.highlightAll()`
4. 코드 하이라이팅

2023-09-12 09:32 UTC, yogjin commented
> 좋습니다!
highlight.js도 필요한 언어를 import해서 하이라이팅을 적용해 볼 수는 없을까요?

[포스팅](https://yogjin.tistory.com/87) 을 참고해주세요!

2023-09-12 14:35 UTC, jeonjeunghoon commented on frontend/src/components/WritingViewer/WritingViewer.tsx
> +      background-color: transparent;
아하 그렇군요! 코드블럭이 굉장히 이뻐졌네요~

2023-09-12 14:36 UTC, jeonjeunghoon commented on frontend/src/hooks/@common/useCodeHighlight.ts
> +};
오 이런 식으로 동적 import가 가능하군요... 👍

2023-09-13 04:38 UTC, nangkyeonglim approved these changes
확인했습니다! 고생하셨습니다~

2023-09-13 07:12 UTC, merged