[FE] 요청 크기 최적화
woowacourse-teams/2023-dong-gle pull request #395
Opened 2023-09-11 12:34 UTC by jeonjeunghoon

### 🛠️ Issue

- close #389 

### ✅ Tasks
요청 크기 줄이기 설정

### ⏰ Time Difference
- 3 + 1

### 📝 Note
- 요청 크기를 줄이면서 이것 저것 플러그인들을 좀 설치했습니다.
- 또한 바벨 로더를 웹팩에 추가했습니다.
- 라이트하우스 점수는 큰 차이를 안보이네요...

최적화 전
<img width="1014" alt="스크린샷 2023-09-11 오후 9 31 49" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/82c2aad1-cad1-4722-82c6-c7a83f3f72a5">
<img width="645" alt="스크린샷 2023-09-11 오후 9 31 54" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/674f23b2-c42b-4006-8186-b8427b13b81a">

최적화 이후
<img width="309" alt="스크린샷 2023-09-11 오후 9 19 39" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/eaaa412a-252f-4bb5-9c73-9dd7ead54a01">
<img width="1439" alt="스크린샷 2023-09-11 오후 9 19 55" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/821adcf0-1deb-44d0-b57a-337e27d557c8">

라이트하우스 최적화 전
<img width="504" alt="스크린샷 2023-09-11 오후 9 32 43" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/f7395888-dd1a-4622-82e4-4820bf806c01">

라이트하우스 최적화 후
<img width="509" alt="스크린샷 2023-09-11 오후 9 19 04" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/44e54388-c6c1-4ded-b403-5c52789c108c">

2023-09-11 15:16 UTC, yogjin requested changes

2023-09-11 15:16 UTC, yogjin commented on frontend/webpack.prod.js
> +  },
chunk로 나누면 어떤 장점이 있나요?
`React.lazy`를 이용할 때 이미 code spliting이라는 장점을 가져갈 수 있다고 생각하는데
그렇다면 `React.lazy`과 chunk를 함께 이용했을 때 어떤 장점을 더 가질 수 있을지 궁금합니다.
또 `React.lazy`를 사용하지 않고 chunk만 이용했을 때도 어떤 장점이 있는지 궁금합니다.

2023-09-11 15:16 UTC, yogjin commented on frontend/src/routes/Router.tsx
> +const ErrorPage = lazy(() => import('pages/ErrorPage/ErrorPage'));
모든 페이지에 lazy를 적용한 구체적인 근거가 있는지 궁금합니다!

2023-09-12 04:52 UTC, jeonjeunghoon commented on frontend/src/types/typing.d.ts
오 좋아요!

2023-09-12 05:05 UTC, jeonjeunghoon commented on frontend/webpack.common.js
> +            loader: 'babel-loader',
스타일드 컴포넌트 코드 최적화를 위해 넣었어요!
babelrc 파일 내부에 plugin 을 사용하려면 바벨 로더를 추가했어야 했는데,
저희는 IE 브라우저를 지원하지 않으니 바벨 로더를 넣을 필요가 없네용
css 최적화는 굳이 하지 않는게 나을 것같네요!

2023-09-12 05:13 UTC, jeonjeunghoon commented on frontend/webpack.common.js
> +    filename: '[name].[contenthash].js',
네 맞습니당

2023-09-12 05:18 UTC, jeonjeunghoon commented on frontend/webpack.common.js
> +      hash: true,
앗 이것도 캐시 버스팅을 위한 설정인데, 위의 설정과 중복되네요 이 부분 지우는게 나을 것같아요~

2023-09-12 05:24 UTC, jeonjeunghoon commented on frontend/webpack.prod.js
> +  plugins: [new Dotenv({ path: './.env.production' }), new CompressionPlugin()],
cloudflare에서 압축 설정이 가능한지 몰랐네요!컴프레션 플러그인도 제거하도록 할게요~

2023-09-12 05:28 UTC, jeonjeunghoon commented on frontend/public/index.html
> +		<link rel="preload" as="image" type="image/svg+xml" href="donggle-logo.svg" />
리소스는 빠르게 가져와야하는게 좋을거라 생각해서 추가했는데, 생각해보니 로고까지 그럴 필요는 없어보이네용 ㅎㅎ

2023-09-12 05:31 UTC, nangkyeonglim requested changes
전체적으로 어떤 것을 적용했고 각각을 적용하기 전/후 결과가 PR에 더 나타나있으면 좋을 것 같아요!
저희 발표할 때도 어떤 것을 얼만큼 어떻게 최적화했는지 발표해야하니까 정리를 해놓으면 좋을 것 같습니다.

2023-09-12 05:31 UTC, nangkyeonglim commented on frontend/.babelrc.json
> +        "displayName": true,
이거 displayName: true로 한 이유가 있을까요?

2023-09-12 05:31 UTC, nangkyeonglim commented on frontend/src/routes/Router.tsx
> +const ErrorPage = lazy(() => import('pages/ErrorPage/ErrorPage'));
적용할 때와 안할 때 요청 크기와 시간 차이도 있었으면 좋겠습니다!

2023-09-12 05:31 UTC, nangkyeonglim commented on frontend/webpack.common.js
> +            loader: 'babel-loader',
그럼 스타일드 컴포넌트 css는 최적화는 진행안하는 건가요?

2023-09-12 05:31 UTC, nangkyeonglim commented on frontend/webpack.prod.js
> +    ],
이거 common에서도 설정했는데 여기서도 해줘야하나요?

2023-09-12 05:31 UTC, nangkyeonglim commented on frontend/webpack.prod.js
> +      }),
저도 저희 서비스에 이미지 에셋이 많지 않아서 굳이 플러그인으로 최적화할 필요는 없다고 생각합니다

2023-09-12 05:43 UTC, jeonjeunghoon commented on frontend/webpack.prod.js
> +      }),
쿠마 의견에 동의하고 해당 인스턴스는 제거했습니다~

2023-09-12 05:47 UTC, jeonjeunghoon commented on frontend/webpack.prod.js
> +    ],
사실 큰 차이는 보이지 않아요.

최적화

전
<img width="211" alt="스크린샷 2023-09-12 오후 2 45 28" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/25802b7c-0a96-4974-af2f-4c0a3633c6ab">

후
<img width="184" alt="스크린샷 2023-09-12 오후 2 45 56" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/a6cf3921-d756-478f-b90b-1d834d938103">

2023-09-12 05:55 UTC, jeonjeunghoon commented on frontend/webpack.prod.js
> +  },
해당 옵션을 사용하면 중복 청크를 제거하고, 병렬로 파일을 다운 받는 장점이 있어서 택했습니다~
제가 알기로 lazy 로딩은 사용자에게 필요한 리소스만 우선적으로 다운받아 페이지 첫 진입 로딩 속도를 줄이는 기술로 알고 있어요
그래서 이 둘의 쓰임새는 좀 다른 것같아요!

2023-09-12 05:59 UTC, jeonjeunghoon commented on frontend/src/routes/Router.tsx
> +const ErrorPage = lazy(() => import('pages/ErrorPage/ErrorPage'));
첫 페이지의 로딩 속도를 위해 위의 페이지들에 레이지를 적용했습니다~
근데 이 부분에 대해 논의가 필요한 것같아요~
어떤 기준으로 lazy 로딩을 적용해야 할지 감이 잡히지가 않네요

2023-09-12 06:01 UTC, jeonjeunghoon commented on frontend/.babelrc.json
> +        "displayName": true,
디버깅할 때 컴포넌트의 클래스네임이 구체적으로 설정되는 옵션으로 알고 있어서 true로 설정했습니다.
그러나 현재는 해당 플러그인을 사용하지 않아 지운 상태입니다~

2023-09-12 06:15 UTC, jeonjeunghoon commented on frontend/webpack.prod.js
> +    ],
위의 코멘트들에 답변을 달 수가 없네요...

1. 적용할 때와 안할 때 요청 크기와 시간 차이도 있었으면 좋겠습니다! -> 밑의 코멘트에 달아두겠습니다!
2. 그럼 스타일드 컴포넌트 css는 최적화는 진행안하는 건가요? -> 음 최적화하려면 바벨로더를 적용해야하는데... css 최적화 때문에 바벨로 트렌스파일링을 해야하나? 하는 의문이 들어요
3. 이거 common에서도 설정했는데 여기서도 해줘야하나요? -> 해당 룰은 지웠습니다~

2023-09-12 06:16 UTC, jeonjeunghoon commented
최적화

전
<img width="211" alt="스크린샷 2023-09-12 오후 2 45 28" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/7d441a4b-41e0-4568-94fe-abe43ca9bbd1">
<img width="566" alt="스크린샷 2023-09-12 오후 3 11 12" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/dff1065b-d56f-4fbb-946a-69d047995bba">
<img width="564" alt="스크린샷 2023-09-12 오후 3 09 37" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/5343d595-7ca5-46b0-bd5a-e4f3d605bf4b">

후
<img width="184" alt="스크린샷 2023-09-12 오후 2 45 56" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/48af9912-659b-4194-a8f2-736e4c3bcc67">
<img width="563" alt="스크린샷 2023-09-12 오후 3 11 46" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/4fe2377e-5148-4834-8457-741270b7043c">
<img width="565" alt="스크린샷 2023-09-12 오후 3 08 56" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/31784f01-1fc0-402b-9adc-7d81098a881d">

거의 차이가 없는 것같아요.. 사실상 이미지 파일 최적화만 진행하면 됐을 것같기도 하네요!
svg 관련해서 더 최적화를 하고 싶은 욕심은 있는데 어떻게 생각하시나요들

2023-09-13 04:40 UTC, nangkyeonglim commented on frontend/webpack.prod.js
> +    ],
Parsed size에 변화가 없는데 최적화가 어떤 점에서 진행이 된 걸까요?🧐

2023-09-13 04:43 UTC, nangkyeonglim commented on frontend/webpack.prod.js
> +    ],
2. css 최적화 할 때랑 안 할때 크기와 시간 차이가 있을 거 같은데 그 트레이드오프를 직접 측정해보면 더 도움될 것 같아요~!

2023-09-14 05:37 UTC, jeonjeunghoon commented
## 최적화 적용 목록

- [x] SVG 파일 최적화
- [x] 이미지 최적화
- [x] 페이지 Lazy 로딩 적용

3G 환경으로 측정한 결과 이미지 최적화와 페이지 Lazy 로딩을 적용했을 때, 유의미한 결과가 나왔습니다.

### SVG 파일 최적화

SVG 파일을 최적화 사이트를 이용해 최적화(중복되고 쓸모없는 정보를 제거, 지오메트리 경로를 단순화)했습니다.

최적화 전/후

<img width="115" alt="스크린샷 2023-09-14 오후 2 34 13" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/f09e1521-39f7-4151-9e8f-84f3304ebace">

<img width="115" alt="스크린샷 2023-09-14 오후 2 33 21" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/53ab7e63-53ba-44ab-996d-51051a7233c3">

### 이미지 최적화

donggle-example.png 파일을 최적화 했습니다.
<img width="505" alt="스크린샷 2023-09-14 오후 2 25 38" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/9789741e-5ea5-4a02-ae45-fdf565aecf3f">

최적화 전 파일은 736KB로 꽤 큰 크기의 리소스입니다. 또한 크기가 다음과 같은데, 저희 서비스에서는 width를 600으로 사용하고 있습니다.
<img width="303" alt="스크린샷 2023-09-14 오후 2 27 17" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/27e1f04b-4d4a-415b-a900-4ce45cd90798">

이러한 파일을 각각 png, webp, avif 포맷으로 최적화했습니다. 각각의 크기는 width 600으로 통일했습니다.

**PNG**
<img width="234" alt="스크린샷 2023-09-14 오후 2 28 29" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/9d4a7313-ae7f-46e9-9bde-8937aab8cebf">

**WEBP**
<img width="239" alt="스크린샷 2023-09-14 오후 2 28 38" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/f5bdf8ca-914d-4d5b-8478-a2dc73a1fded">

**AVIF**
<img width="234" alt="스크린샷 2023-09-14 오후 2 28 48" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/7c469932-416a-4d6b-8753-a407949bcb8e">

### 페이지 Lazy Loading 적용

WritingPage 는 코드 블럭을 위한 패키지로 Primejs를 사용하기 때문에 패키지 크기가 큽니다.
따라서 Lazy를 적용하는 것이 효율적이라 판단하여 적용했습니다.

IntroducePage는 사용자가 로그인 되어 있을 경우엔 접근할 일이 없는 페이지입니다.
따라서 Lazy를 적용했습니다.

**최적화 전 Finish: 13.08s**
<img width="753" alt="스크린샷 2023-09-14 오후 1 57 25" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/713a0f89-d0c9-42d2-af93-d6404efb2992">

**이미지 최적화 적용 Finish: 9.07s**
<img width="752" alt="스크린샷 2023-09-14 오후 1 59 05" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/dab83f84-d3bf-4bdd-9558-8a0d8028d600">

**Lazy 로딩 적용 Finish: 6.80s**
<img width="754" alt="Lazy" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/d1aaf5da-c672-433b-bfe7-62b33eea13fe">

2023-09-14 05:45 UTC, nangkyeonglim commented on frontend/src/routes/Router.tsx
> +const WritingPage = lazy(() => import('pages/WritingPage/WritingPage'));
쿠마가 적용한 거 반영되면 prismjs를 동적 import로 가져오는데 페이지 자체도 동적으로 가져올 필요가 있나요?

2023-09-14 06:04 UTC, jeonjeunghoon commented on frontend/src/routes/Router.tsx
> +const WritingPage = lazy(() => import('pages/WritingPage/WritingPage'));
아 맞네요 그 부분 생각 못했네요 WritingPage 는 뺄게요

2023-09-14 06:26 UTC, nangkyeonglim commented on frontend/src/routes/Router.tsx
> +const WritingPage = lazy(() => import('pages/WritingPage/WritingPage'));
좋습니다~!

2023-09-14 06:27 UTC, nangkyeonglim approved these changes
고생많으셨어요!
최적화는 역시 어렵네요..

2023-09-15 01:29 UTC, yogjin requested changes

2023-09-15 01:29 UTC, yogjin commented on frontend/src/assets/icons/donggle-example-png.png
해당 이미지가 레티나 디스플레이(맥)에서 윈도우 대비 2배 흐릿하게 보이는 아쉬움이 있네요..
[이 글](https://doridori-samsam.tistory.com/28)을 참고해주시면 좋을 것 같아요.
유저가 동글 방문 시 볼 수 있는 첫 이미지인 만큼 첫 인상이 중요하다고 생각해서 수정 제안드립니다.

2023-09-15 14:52 UTC, yogjin commented
레티나 적용하니까 훨씬 좋네요!
수고하셨습니다.

2023-09-16 07:07 UTC, merged