[FE] 발행된 글로 이동하는 기능 구현
woowacourse-teams/2023-dong-gle pull request #408
Opened 2023-09-14 07:19 UTC by jeonjeunghoon

### 🛠️ Issue

- close #391 

### ✅ Tasks
- [x] mock 데이터 수정
- [x] `PublishedDetail` 타입 수정
- [x] 블로그 링크로 이동하는 기능 추가

### ⏰ Time Difference
- 0.5

### 📝 Note

API 명세의 수정으로 `PublishedDetail` 타입이 수정되었습니다.

```typescript
export type PublishedDetail = {
  blogName: Blog;
  publishedAt: Date;
  tags: string[];
  publishedUrl: string;
};
```

따라서 서버 API가 변경 완료되면, 그때 이 브랜치가 머지되어야 할 것같네요~

2023-09-14 07:47 UTC, nangkyeonglim approved these changes
드디어 링크가 생겼네요 좋습니다~!

2023-09-15 01:44 UTC, yogjin requested changes
수고하셨습니다~ 코멘트 하나 확인해주세요!

2023-09-15 01:44 UTC, yogjin commented on frontend/src/components/WritingPropertySection/WritingPropertySection.tsx
> +                      ) : null}
publishedUrl이 null 인 경우를 대응할 필요는 없을 것 같아요.
publishedUrl의 타입 선언이 `string`이기도 하고, `writingInfo`가 있다면 publishedUrl이 존재하는게 확신하다고 생각합니다.

2023-09-15 01:46 UTC, nangkyeonglim commented on frontend/src/components/WritingPropertySection/WritingPropertySection.tsx
> +                      ) : null}
궁금한게 있는데 이거 없으면 "" 빈스트링으로 오나요?

2023-09-15 01:48 UTC, jeonjeunghoon commented on frontend/src/components/WritingPropertySection/WritingPropertySection.tsx
> +                      ) : null}
아 이 부분에 대해 제가 PR에 적었어야 했는데 깜빡했네요 ㅜㅜ
해당 기능이 추가되기 전에 발행을 한 케이스들에 대해 방어한 로직이에요.
`PubilshedUrl` 타입을 `string | null` 로 했어야 했는데 그 부분은 미처 수정을 못했네요.
이 부분 수정해서 커밋했습니다!

2023-09-15 01:51 UTC, jeonjeunghoon commented on frontend/src/components/WritingPropertySection/WritingPropertySection.tsx
> +                      ) : null}
`null` 로 옵니다~!

2023-09-15 02:11 UTC, yogjin requested changes

2023-09-15 02:11 UTC, yogjin commented on frontend/src/components/WritingPropertySection/WritingPropertySection.tsx
> +                      ) : null}
아.. 이전 발행이 문제가되네요😱
그럼 주석을 하나 달아놓으면 좋을 것 같습니다.
+ 삼항연산자 대신 `Boolean(PubilshedUrl) && <발행컴포넌트>`는 어떨까요?

2023-09-15 02:47 UTC, yogjin approved these changes
`Boolean(publishedUrl)` && 로 하면 타입 좁히기가 안되는 문제점이 있군요!
수고하셨습니다~

2023-09-15 03:07 UTC, merged