[BE] feat: AOP를 이용한 사용자의 중복실행(글,카테고리 추가) 막기
woowacourse-teams/2023-dong-gle pull request #416
Opened 2023-09-16 10:08 UTC by ingpyo

### 🛠️ Issue

- close #415
### ✅ Tasks
-  Aop를 활용한 사용자 하나의 프로세스에 락을 거는 로직 추가

### ⏰ Time Difference
- 3

2023-09-18 04:54 UTC, ezzanzzan approved these changes
구웃...👍

2023-09-18 04:54 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/NoConcurrentAccessAspect.java
> +    private final ConcurrentHashMap<Long, Lock> memberLock = new ConcurrentHashMap<>();
개행 추가 해주세용 ㅎㅎ

2023-09-18 04:54 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/NoConcurrentAccessAspect.java
> +    }
와우 ... 👍

2023-09-18 05:26 UTC, HubCreator approved these changes

2023-09-18 05:26 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/NoConcurrentAccessAspect.java
> +            throw anno.value().getDeclaredConstructor().newInstance();
annotation에서 정의한 예외를 던진다! 애너테이션에서 예외를 관리할 수 있어서 응집도 있고 좋네요! ㅎㅎㅎ

2023-09-18 05:26 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/NoConcurrentAccessAspect.java
> +        final Long memberId = (Long) joinPoint.getArgs()[MEMBER_ID_INDEX];
메서드 인자 중 첫 번째 인자를 MEMBER_ID라고 가정하고 memberId를 추출하네요! 이부분은 동글 팀원들 모두가 주의해야 할 것 같네요 ㅎㅎㅎ 아니면 인자의 갯수만큼 반복문을 돌면서 Long memberId를 찾아야 할 것 같은데 다들 조심조심!!

2023-09-18 05:26 UTC, HubCreator commented on backend/src/main/java/org/donggle/backend/application/NoConcurrentAccessAspect.java
> +            lock.unlock();
만약 `@NoConcurrentExecution` 애너테이션이 붙은 메서드를 1000명의 서로 다른 사용자가 호출한다면, ConcurrentHashMap에 1000개의 key-value가 누적 저장될 것 같아요. finally 블록에서 바로 map에 해당 memberId 값을 지워줘도 좋을 것 같네요.

2023-09-18 05:26 UTC, HubCreator reviewed
고생하셨습니다!!

2023-09-18 13:03 UTC, echo724 requested changes
수고하셨습니다. 학습량이 많았을 것으로 보이는데 주말 내내 동글만 팠나보네요,, 멋집니다! 다른 분들 리뷰는 반영되면 좋을 것 같아서 request chagnes로 할게요!

2023-09-18 13:03 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/config/InitLocalAndTestData.java
> +            credentials2.updateMediumToken("핑에크코");
오,, 저만 없어서 넣어준건가요? 땡큐 ㅋㅋㅋ

2023-09-19 08:33 UTC, echo724 approved these changes

2023-09-19 08:35 UTC, merged