[BE] refactor: 회원조회할때 커버링 인덱스가 적용되도록 수정
woowacourse-teams/2023-dong-gle pull request #424
Opened 2023-09-18 05:27 UTC by ingpyo

### 🛠️ Issue

- close #421

### ✅ Tasks
-  memberAuth DTO도입 후 로그인 로직에 적용

### ⏰ Time Difference
- 1

2023-09-18 13:23 UTC, echo724 requested changes
굿굿! 이번에 진짜 많이 했네요,,, 굿입니다.  다만.. 현재 UserInfo와 MemberInfo가 헷갈립니다. 이름으로 변경되면 좋을 것 같네요!

2023-09-18 13:23 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/service/auth/AuthService.java
> +        return createTokens(initializeMember(userInfo));
```java
public TokenResponse login(final UserInfo userInfo) {
return memberRepository.findBySocialId(userInfo.socialId())
.map(memberInfo -> new Member(memberInfo.id(), new MemberName(userInfo.nickname()), memberInfo.socialId()))
.map(this::createTokens)
.orElse(createTokens(initializeMember(userInfo)));
}
```
1. Optional.map을 사용하는건 어떨까요?!
2. UserInfo와 MemberInfo가 헷갈립니다!

2023-09-18 13:23 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/repository/MemberInfo.java
> +public record MemberInfo(
UserInfo와 헷갈리는데 MemberIndex, MemberIds 이런식의 이름은 어떨까요?

2023-09-18 16:31 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/application/service/auth/AuthService.java
> +        return createTokens(initializeMember(userInfo));
딱 이부분이 고민이였는데 감사합니다 파덜,,,,

2023-09-18 16:32 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/application/repository/MemberInfo.java
> +public record MemberInfo(
socialUserInfo라고 했는데 어색할까요??

2023-09-19 07:35 UTC, HubCreator approved these changes

2023-09-19 07:35 UTC, HubCreator approved these changes

2023-09-19 07:36 UTC, HubCreator approved these changes

2023-09-19 08:36 UTC, echo724 approved these changes

2023-09-19 08:36 UTC, merged