[BE] refactor: 여러번 쿼리나가는 글 가져오기, 글 발행정보 쿼리 수정
woowacourse-teams/2023-dong-gle pull request #426
Opened 2023-09-18 05:54 UTC by ingpyo

### 🛠️ Issue

- close #425

### ✅ Tasks
- 글을 가져올때 글의 블럭마다 select쿼리를 날리는 로직 in절 추가
- 블로그 발행 여부 쿼리 JOIN FETCH추가

### ⏰ Time Difference
- 2

2023-09-18 13:15 UTC, echo724 requested changes
치명적인 오류가 있어서 request changes를 요청합니다! 그치만 쿼리를 일일이 분석해보는 열정... 멋지고 배우고 싶네요!

2023-09-18 13:15 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
> +
이 부분 아까 얘기 나눴었는데 완전히 사용하는데가 다른 메서드인 것 같아요!

2023-09-18 13:15 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
> -    @Query("select w from Writing w join fetch w.blocks where w.id = :writingId")
findByIdWithBlocks는 발행과 렌더를 하기 위한 Status=Active인 글과 blocks를 같이 가져오는 메서드입니다.

2023-09-18 13:15 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/service/writing/WritingService.java
> +        return writing;
이 부분 메서드로 분리하면 좋을 것 같네요! 아니면 적어도 NormalBlock으로 변경하는 부분은 분리하면 좋을 것 같아요!

2023-09-18 13:15 UTC, echo724 commented on backend/src/main/java/org/donggle/backend/application/service/writing/WritingService.java
> +        final List<WritingDetailResponse> responses = sortedWriting.stream()
이부분도 depth가 깊은데 분리하면 좋을것 같아요!

2023-09-18 14:44 UTC, ezzanzzan approved these changes
내일 전체적인 코드에 대해서 다시 한 번 설명 부탁드려요 ㅠㅠ

2023-09-18 14:44 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/service/CategoryService.java
> +    }
이름이 "기본"이라고 해서 BasicCategory가 될 수 없어요 !

2023-09-18 14:44 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
> +    Optional<Writing> findByMemberId(@Param("memberId") final Long memberId, @Param("writingId") final Long writingId);
`@EntityGraph`가 아니라 join fetch를 사용한 이유가 있을까요 ?

2023-09-18 14:44 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/service/CategoryService.java
> +    }
기본 카테고리를 쿼리로 실행하지 않고 찾고 싶다면, findAllByMemberId가 PK 순서대로 가져와지는걸 보장된다면 가능할 것 같네요 ˙ᵕ˙ 순서가 보장되면 첫 번째 카테고리를 가져오면 그게 기본 카테고리가 될 것 같아요

2023-09-18 14:44 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/repository/BlogWritingRepository.java
> +    List<BlogWriting> findWithFetch(@Param("writings") List<Writing> writings);
어디에서 사용되나요 ??

2023-09-18 17:29 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/service/CategoryService.java
> +    }
맞아요 ! 
1. 멤버가 가지고 있는 카테고리의 첫번째가 Basic 카테고리이다.
2. `기본`이라는 이름을 가진 카테고리는 반드시 Basic 카테고리인 것은 아니다.
라는 말이었어요 !!

근데 다시 생각해보니까 중복 이름 검증 로직이 있어서 기본 카테고리가 기본이 되겠네요 죄송합니다 🥲
저번에 이름으로 검증했다가 오류 터졌어서 그거랑 잠깐 헷갈렸네요 굿굿 👍

2023-09-18 17:30 UTC, ezzanzzan commented on backend/src/main/java/org/donggle/backend/application/repository/WritingRepository.java
> +    Optional<Writing> findByMemberId(@Param("memberId") final Long memberId, @Param("writingId") final Long writingId);
제가 알기로 `join fetch`는 inner join이고, `EntityGraph`는 left join이라고 알고 있어요 !
EntityGraph를 사용하면 저렇게 쿼리를 하나하나 작성하지 않아도 되기도 하구요 내일 같이 얘기해봐요 ~ 🌈

2023-09-19 10:10 UTC, echo724 approved these changes

2023-09-19 10:10 UTC, merged