[FE] 글 발행 기능 구현
woowacourse-teams/2023-dong-gle pull request #46
Opened 2023-07-14 06:52 UTC by jeonjeunghoon

### 🛠️ Issue

- close #27 

### ✅ Tasks

- [x] 글 발행 버튼 파일 스토리북 연동
- [x] 글 발행 버튼 컴포넌트 구현
- [x] API 요청 로직 작성

### ⏰ Time Difference
- 예상보다 1시간 덜 걸림

### 📝 Note
-

2023-07-15 15:01 UTC, nangkyeonglim requested changes
API랑 버튼 추상화 된 걸로 바꾸면 코드가 많이 없어질 것 같아서 그거는 감안하고 리뷰했습니다!
추가로 font-size, weight, line-height도 따로 빼는 거 논의해보면 좋을 것 같아요👍

2023-07-15 15:16 UTC, yogjin requested changes
수고하셨어요~ 코멘트 확인해주세요.
한가지 궁금한 점이 있는데, `PublishingSection` 컴포넌트는 #49 에 있는 `WritingPage` 내부에서 추후 만들어질 오른쪽 사이드바에 들어가는 게 맞을까요?

2023-07-15 15:16 UTC, yogjin commented on frontend/src/components/BlogButton/BlogButton.tsx
> +  // TODO: 쿠마 버튼 완성되면 컴포넌트 교체
저도 `BlogButton`은 따로 없어도 될 것 같아요

2023-07-15 15:16 UTC, yogjin commented on frontend/src/components/BlogList/BlogList.tsx
> +const BlogList = () => {
`BlogPublishButtonList` 처럼 더 구체적인 네이밍이면 좋을 것 같아요.
처음 `BlogList` 를 봤을 때 어떤 컴포넌트인지 예측이 잘 안갔습니다🥲

2023-07-17 04:44 UTC, jeonjeunghoon commented on frontend/src/components/BlogButton/BlogButton.tsx
> +  // TODO: 쿠마 버튼 완성되면 컴포넌트 교체
동의합니당~

2023-07-17 04:44 UTC, jeonjeunghoon commented on frontend/src/components/BlogList/BlogList.tsx
> +      {Object.values(BLOG).map((name) => {
모든 블로그 리스트를 보여줄지 아니면 연동된 블로그 리스트만 보여줄지 따로 논의가 필요할 것같아요!

2023-07-17 08:33 UTC, jeonjeunghoon commented
> 

네 맞습니다~!
PublishingSection은 추후에 사이드바에 들어갈 부분입니다.

2023-07-17 12:57 UTC, nangkyeonglim requested changes
확인하시고 수정부탁드려요!

2023-07-17 12:57 UTC, nangkyeonglim commented on frontend/src/components/BlogPublishButtonList/BlogPublishButtonList.tsx
> +              onClick={() => publishWriting(writingId, body)}
이 부분 인라인 함수말고 따로 빼주면 좋을 것 같아요!

2023-07-17 12:57 UTC, nangkyeonglim commented on frontend/src/components/BlogPublishButtonList/BlogPublishButtonList.tsx
> +        const body: PublishWritingRequest = { publishTo: name };
이 부분도 onClick 핸들러 따로 빼면 없어도 될 거 같아요

2023-07-17 12:58 UTC, yogjin requested changes
수고하셨어요~ 수정사항 코멘트로 남겨두었습니다.

2023-07-17 12:58 UTC, yogjin commented on frontend/src/components/PublishingSection/PublishingSection.tsx
> +const PublishingSection = ({ writingId }: PublishingSectionProps) => {
컨벤션에 맞게 `PublishingSectionProps` 네이밍 `Props`로 바꿔주세요~

2023-07-17 12:58 UTC, yogjin commented on frontend/src/components/BlogPublishButtonList/BlogPublishButtonList.tsx
> +const BlogPublishButtonList = ({ writingId }: BlogPublishButtonListProps) => {
여기도 `BlogPublishButtonListProps` 네이밍 바꿔주세요~

2023-07-17 12:58 UTC, yogjin commented on frontend/src/components/BlogPublishButtonList/BlogPublishButtonList.tsx
> +              onClick={() => publishWriting(writingId, body)}
`publishWriting` api 바로 사용하지 않고 `useMutationQuery` 이용하는걸로 바꿔주세요~

2023-07-18 07:23 UTC, jeonjeunghoon commented
### 로딩 중인 상태입니다.

<img width="312" alt="스크린샷 2023-07-18 오후 4 20 58" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/830d708a-8600-400f-b10a-e331fe0cfa29">

### 배포 완료된 상태입니다.

<img width="312" alt="스크린샷 2023-07-18 오후 4 21 46" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/4fcb5078-71bb-4235-9bd1-c0bd3be642f8">

배포 버튼 컴포넌트를 따로 빼놨습니다.
`useMutation` 에서 반환하는 `isLoading` 을 각각의 버튼 컴포넌트에 적용하기 위해서 어쩔 수 없이 분리했습니다.
또한 배포 성공 여부도 따로 전달해줘야 하는 이슈도 있었습니다.

2023-07-18 07:49 UTC, jeonjeunghoon commented
### 추가한 일

- [x] .eslintrc 파일 tsconfig 경로: `./fronted` -> `.` 로 수정
- [x] 발행 api 통신 성공, 실패 여부 UI에 나타내기

2023-07-18 07:58 UTC, nangkyeonglim requested changes

2023-07-18 07:58 UTC, nangkyeonglim commented on frontend/src/components/BlogPublishButtonItem/BlogPublishButtonItem.tsx
> +  const publishWritingToBlog = async (name: PublishToArg) => {
```suggestion
  const publishWritingToBlog = (name: PublishToArg) => async () => {
```
커링함수(밑에 리뷰 참고)

2023-07-18 08:02 UTC, jeonjeunghoon commented
또 다른 커밋 죄송합니다.
배포 버튼 리스트를 PublishingSection과 병합하는 것을 깜빡해서 처리하고 다시 올렸습니다.
또한 Layout 패딩 style과 import문이 조금 수정됐습니다.

양해 부탁바랍니다 ...

2023-07-18 08:10 UTC, jeonjeunghoon commented on frontend/src/components/BlogPublishButtonItem/BlogPublishButtonItem.tsx
> +        onClick={() => publishWritingToBlog(name)}
질문) 이런 방식으로 리팩터링하는 이유가 리렌더링될 때, 함수가 계속 생성되서 그런게 맞나요?

2023-07-18 08:11 UTC, yogjin commented on frontend/src/components/BlogPublishButtonItem/BlogPublishButtonItem.tsx
> +  const publishWritingToBlog = async (name: PublishToArg) => {
커링관련 [좋은 강의](https://www.youtube.com/watch?v=LD97A_gqhzM&t=172s)가 있다네요~

2023-07-18 08:12 UTC, yogjin commented on frontend/src/pages/Layout/Layout.tsx
> +  padding: 20px;
`rem`....

2023-07-18 08:32 UTC, nangkyeonglim approved these changes

2023-07-18 08:32 UTC, nangkyeonglim commented on frontend/src/components/BlogPublishButtonItem/BlogPublishButtonItem.tsx
> +  BlogPublishButtonItem: styled.li<Record<'$isLoading', boolean>>`
```suggestion
  BlogPublishButtonItem: styled.li<{$isLoading: boolean}>`
```

2023-07-18 09:39 UTC, yogjin approved these changes

2023-07-18 09:39 UTC, merged