[FE] 레이아웃 구현
woowacourse-teams/2023-dong-gle pull request #49
Opened 2023-07-14 08:37 UTC by jeonjeunghoon

### 🛠️ Issue

- close #25 

### ✅ Tasks
- [x] Layout 컴포넌트로 큰 틀 구현
- [x] WritingPage 컴포넌트로 Main 부분 구현

### ⏰ Time Difference
- 0

### 📝 Note
- 디자인이 애매해요

2023-07-15 14:53 UTC, yogjin approved these changes
수고하셨어요~ 레이아웃 잘 만들어주셨네요.
그런데 컴포넌트 사용법과 실행화면까지 함께 알려주셨으면 더 좋았을 것 같아요.
```typescript
<Layout>
  <WritingPage></WritingPage>
</Layout>
```

<img width="1503" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/1682d12c-6e5b-4bb4-b18e-ff0a49433e7e">


이렇게 사용하고 고정된 Layout 속에서 Page를 알아끼는걸 의도하신것 맞죠?

2023-07-15 14:53 UTC, yogjin commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    border: 3px solid black;
@nangkyeonglim
여기 `3px`도 rem으로 바꿔야할까요?

2023-07-15 14:53 UTC, yogjin commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    background-color: white;
이런 색상 부분은 나중에 머지되면 theme으로 리팩터링 하면 되겠네요.

2023-07-15 15:26 UTC, nangkyeonglim requested changes
레이아웃 부분은 일단 지금 구현하기에 살짝 애매한 거 같은데 나중에 좀 수정이 많이 들어갈 수도 있을 것 같네요..!
쿠마 말대로 사용법도 좋은데 지금은 페이지 하나니까 그냥 App에 바로 넣어놔도 될 것 같습니다!

2023-07-15 15:26 UTC, nangkyeonglim commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    border: 3px solid black;
border 굵기 같은 경우는 다를 필요 없을 거 같아서 px 해도 될 거 같아요

2023-07-15 15:26 UTC, nangkyeonglim commented on frontend/src/pages/Layout/Layout.tsx
> +    border: 3px solid black;
이거 border 시안에 2px로 나와있어서 수정해야할 거 같아요
그 6월부터 figma에 원래 css 코드 나오던 inspect창이 개발자 모드 켜야 보인다하더라고요
헤더에 share옆에 `</>` 이렇게 생긴 토글버튼 키면 보여요!

2023-07-16 09:17 UTC, jeonjeunghoon commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    border: 3px solid black;
저도 궁금했습니당~ 더불어 outline 같은 속성도 rem으로 할지 px로 할지 혼란스러워요

2023-07-16 10:26 UTC, jeonjeunghoon commented
### ✅ Tasks
- [x] Layout 컴포넌트, WritingPage 컴포넌트에서 재사용되는 css 속성들 상수로 분리

### 📝 Note

리팩터링하고 올리는 과정에서 이슈가 생겼어요

develop 브랜치에서 `pull origin develop` 하고

layout 브랜치에서 작업한 이후 `stash` -> `rebase develop` -> `stash pop` -> `pull origin feature/layout-25` -> `push origin feature/layout-25` 하니까 commit에 api 관련 커밋이 들어가버렸어요.

우선 충돌은 없는 것같아서 pr 올립니다

<img width="1552" alt="스크린샷 2023-07-16 오후 6 57 06" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/fc95ee5d-5afc-4a5f-a091-b7a83deba413">

### 사용법
```typescript
const App = () => {
  return <Layout>
    <WritingPage />
  </Layout>;
};
```

2023-07-16 10:57 UTC, nangkyeonglim commented on frontend/src/pages/WritingPage/WritingPage.tsx
> +    border: 3px solid black;
width height font만 해도 될 거 같아요

2023-07-16 11:00 UTC, nangkyeonglim approved these changes
수정해주신거 확인했습니다!
일단 레이아웃은 이 정도로 하고 나중에 점차 리팩토링 하면 좋을 것 같아요
고생하셨습니다~

2023-07-16 11:00 UTC, merged