[FE] refactor: 전체적인 모킹 서버(msw) 로직 정비
woowacourse-teams/2023-dong-gle pull request #499
Opened 2023-10-01 06:46 UTC by yogjin

### 🛠️ Issue

- close #491

### ✅ Tasks
- msw 핸들러의 모든 로직을 정비
- 성공(200, 201, 204) 하는 경우만 모킹, 에러 상황은 모킹하지 않음

### ⏰ Time Difference
- 8 + (12)

### 📝 Note
저희가 모킹을 이용해서 cypress 테스트를 작성하고자 했어서,
먼저 사전작업으로 msw 로직을 전부 재정비했습니다.

그런데 어떻게 msw 로직을 구성해야할 지 고민이 많았어요.

처음엔 db처럼 배열 하나를 선언해서 그 배열에 글과 카테고리를 담은 다음, 각 핸들러에서 해당 배열을 조작하는 식으로 하려고 했으나,
이 방법은 내가 마치 백엔드가 된 기분이었어서 배(실제 구현)보다 배꼽(모킹 구현)이 더 커지는 상황이었습니다.

그래서 브라우저에서 데이터가 렌더링 되는 부분(`...Page`)에 따라 배열을 따로 구성했습니다.
그 배열들은 src/mocks/data 에 들어가 있어요.
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/e5f24309-9690-4c03-9751-b754396d19e3)
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/4473c8e3-624f-406e-8e31-1c6e01c36cf5)
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/d864b36f-6063-4a4a-bc2d-9ff32d963170)
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/d137be96-d904-4226-ac0c-24409a5b8a16)
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/f6bb1747-5ed9-453e-b756-d16ba4bc2b67)
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/9fee1069-a9b2-492a-9e49-e43145f9a774)

보이는 부분에 따라 배열을 나눴기 때문에, mutation api(`patch`, `delete`, `post`) 핸들러에서는 변화를 줘야하는 배열들의 데이터를 조작해야합니다. 그러면 프론트에서 `get`을 요청했을때 변화된 배열을 바르게 보내줄 수 있겠죠.
하지만 여기서도 어느 정도까지 배열조작을 디테일하게 구현해야할 지 경계가 모호합니다.
그 부분에 대해서는 각자 알잘딱하게 구현하는 걸로 맡기는 게 좋다고 생각했어요.

예를 들어 글을 조회할 때, 모든 글이 같은 글을 던져주는 것 처럼요
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/ad667d66-e84c-4046-b7e8-0e3e15830f9a)

https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/ed64772f-e64a-4220-873b-6a4b64a643df

다만 진짜로 보이는 부분에 대해 자신감을 가지고 싶은 부분에 대해서는 
테스트 배열을 잘 조작하여 핸들러를 구성하면 됩니다.

예를 들어 저는 글 삭제, 복구를 했을 때 의도대로(휴지통에 글이 들어가고, 복구 시 왼쪽 사이드바 카테고리 글을 invalidate 하는지) 동작하는지 보고 싶었습니다.
![화면 기록 2023-10-01 오후 3 26 57](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/462f399f-9649-439b-8f96-25bf39361546)
그러면 그와 관련된 `category.ts`, `trashCanPage.ts` 파일에 있는 데이터를 조작하면 됩니다.
여기서 포인트는 삭제된 글의 제목이 실제 삭제된 것과 다르다는 것입니다.
즉, 로직을 너무 구체적으로 작성하지 않아도 되고, 해당 '동작' 을 프론트에서 확인 할 수 있게만 목 데이터를 넣어준다면 충분하다고 생각합니다.
경우에 따라 구체적으로 작성해야할 때도 있긴 하겠지만요.

### 참고
해당 이미지에 있는 모든 api(`글 순서 변경` 제외)에 대한 모킹을 완료했습니다.
<img width="1497" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/22b2653e-c170-4116-9692-0d11478e00d7">

각 렌더링 부분에 따라 `get` 메서드가 있으면 데이터 배열을 만들었습니다.
그래서 mocks/data 내부 파일이 6개 입니다.
<img width="1226" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/dc5c2c78-bd23-4e52-b7de-514424e35af1">
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/e5f24309-9690-4c03-9751-b754396d19e3)

2023-10-02 12:47 UTC, jeonjeunghoon requested changes
고생 많으셨어요!!

의논할 점은 코멘트에 남겨뒀습니다~ ㅎㅎ

2023-10-02 12:47 UTC, jeonjeunghoon commented on frontend/src/mocks/handlers/trash.ts
> +    }
꼼꼼한 처리 좋네요~

2023-10-02 14:40 UTC, nangkyeonglim requested changes

2023-10-02 14:40 UTC, nangkyeonglim commented on frontend/src/mocks/data/category.ts
> +  });
흠 이게 한번만 유효한 동작이어서 애매한 거 같긴한데 이렇게 수정해보면 어떨까요?

1. `writingsIn**카테고리`를 없애고 이런 형태로 카테고리와 글을 합친다.
<img width="487" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/593333e9-dcdf-41ec-8df5-02b4241b0bdc">

2. `getWritingsIn사이드바카테고리`를 이런식으로 수정한다.
<img width="585" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/63f6e537-a417-454d-b8ee-c19160cfec33">

3. `addCategory`시 로직을 이렇게 바꾼다. 
(아커 꺼에서 조금 수정해서 최대값을 찾아서 +1로 바꾸기 -> length로 하면 id가 1,2,3 있는 형태에서 2를 지우고 addCategory하면 3이 되므로.. )

<img width="590" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/c75da15d-862b-4014-a18d-1930c3a353d5">

4. 나머지 로직을 조금조금 바꿔보면 이쪽 로직은 완벽할 것 같아요

+) sameKey오류도 사라질 것 같아요
<img width="641" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/9105ef6a-c341-4a57-b802-9de13fa984e3">

2023-10-02 14:40 UTC, nangkyeonglim commented on frontend/src/mocks/data/homePage.ts
> +  content: [
이게 조금 애매한게 물론 재사용할 수 있으면 좋겠지만 category내에 writings가 있는 형태가 아니라서 형식이 살짝 달라서 조금 어려울것 같긴하네요..

2023-10-02 14:40 UTC, nangkyeonglim commented on frontend/src/mocks/data/trashCanPage.ts
> +    title: `나도 버려졌어 ${writingId}`,
<img width="236" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/5ab06f82-da75-4872-a5f9-dcd66b62550a">

writingId가 2면 id가 3되고 나도 버려졌어 3이 되서 살짝 불편스하네요.. ㅎㅎ
title에서 ++ 해주는 거 어떤가요?

2023-10-02 14:40 UTC, nangkyeonglim commented on frontend/src/mocks/handlers/category.ts
>      if (!isValidAccessToken(req)) return res(ctx.status(401), ctx.json(ERROR_RESPONSE));
혹시 이 부분을 앞단에서 미리 잡을 수 있는 방법은.. 못찾으셨나요😢

2023-10-02 14:40 UTC, nangkyeonglim commented on frontend/src/mocks/handlers/utils.ts
> +
ctx를 나눠놓은 것 좋네요!

2023-10-03 02:50 UTC, jeonjeunghoon commented on frontend/src/mocks/data/trashCanPage.ts
> +    title: `나도 버려졌어 ${writingId}`,
오 ... 그러게요 예리하네요 파인

2023-10-03 02:50 UTC, jeonjeunghoon commented on frontend/src/mocks/data/trashCanPage.ts
> +    title: `나도 버려졌어 ${writingId}`,
아니면 writingId를 0으로 잡고 id에서 ++writingId 처럼 해도 될듯용

2023-10-03 06:27 UTC, yogjin commented on frontend/src/mocks/data/category.ts
> +  });
카테고리 추가하는 로직은 아커가 제안한 것 처럼 하면 좋다고 생각합니다.
카테고리 삭제 시 오류가 나는 건 삭제한 카테고리 내부 글을 기본 카테고리로 옮길 때 발생하고 있었네요.
<img width="729" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/311932e3-f518-42d3-9388-45fc27bcf0e8">
다음과 같이 빈 배열을 추가해서 해결했습니다.
오류가 나는 부분에 대해 해결은 했지만,

파인이 제시한 
> 1. writingsIn**카테고리를 없애고 이런 형태로 카테고리와 글을 합친다.

부분에 대한 제 생각은 이렇습니다.
현재 모킹 로직을 최대한 단순하게 가져가려고 했는데요,
그래서 get api가 들어오면, 데이터가 담긴 배열을 메서드를 통해 가져오는 게 아니라, 기존 배열을 바로 리턴하도록 설계했습니다.
이런 느낌입니다.
<img width="453" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/ddc18b04-7be5-4ecb-8799-dd4bcd0bf6e6">
<img width="795" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/4ae70795-f465-45c8-9da5-865b856a6d84">
즉 get api는 각자의 배열을 가지고 있는 셈이죠. mutation들은 이 get 배열들을 조작하고 있습니다.

만약 
`writingsIn**카테고리` `categories` 배열을 합친다면, 그 합친 배열을 이용하는 get api는 각 response json 타입에 맞게 가공해서 응답해줘야하는데, 그럼 그 가공작업을 해주는 유틸성격의 함수가 늘어나게되고, 모킹 로직이 복잡해진다고 생각합니다
그래서 배열을 나누어서 관리하면 좋다고 생각합니다🙂

2023-10-03 06:30 UTC, yogjin commented on frontend/src/mocks/data/homePage.ts
> +  content: [
똑같이 위에서 언급한 부분인 것 같아요.
각 get api들은 각자의 배열을 가지고 있는 게 좋다고 생각합니다.
파인이 언급한 것 처럼 형식이 다르기 때문에 로직이 복잡해질 것 같아요.

2023-10-03 07:34 UTC, yogjin commented on frontend/src/mocks/handlers/category.ts
>      if (!isValidAccessToken(req)) return res(ctx.status(401), ctx.json(ERROR_RESPONSE));
네.. 못찾았습니다ㅠ

2023-10-03 11:42 UTC, nangkyeonglim commented on frontend/src/mocks/handlers/category.ts
>      if (!isValidAccessToken(req)) return res(ctx.status(401), ctx.json(ERROR_RESPONSE));
😢

2023-10-03 11:46 UTC, nangkyeonglim commented on frontend/src/mocks/data/category.ts
> +  });
아 GET 쪽에서 저렇게 가져오고있었네요!
> 그 가공작업을 해주는 유틸성격의 함수가 늘어나게되고

이 부분에 동의합니다 그럼 기존 방식이 좋을 것 같아요

다만 카테고리 추가 로직에서 length를 기준으로 하면 
id가 1,2,3 있는 형태에서 카테고리 2를 지우고 addCategory하면 3이 되서 1,3,3 이렇게 되는데
최대값을 찾아서 +1로 바꾸는 거 어떨까요?
![image](https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/8baaf984-1d94-4896-b300-ad0ba2defed9)

2023-10-03 11:47 UTC, nangkyeonglim requested changes
나머지는 확인하였습니다 추가 코멘트만 확인해주세요!

2023-10-03 14:11 UTC, yogjin commented on frontend/src/mocks/data/category.ts
> +  });
> 최대값을 찾아서 +1로 바꾸는 거 어떨까요?

좋아요~ 반영했습니다.

2023-10-04 03:35 UTC, nangkyeonglim approved these changes
좋습니다 너무 고생하셨어요!!

2023-10-04 08:40 UTC, jeonjeunghoon approved these changes
확인했습니다! 고생 많으셨어요~!

2023-10-04 08:45 UTC, merged