[FE] feat: `Button` 컴포넌트 추가
woowacourse-teams/2023-dong-gle pull request #50
Opened 2023-07-14 11:00 UTC by yogjin

### 🛠️ Issue

- close #42

### ✅ Tasks
- Button 컴포넌트 추가
- Button 스토리 추가
- `theme` gray color 추가
- `theme` color의 타입인 `Color` 추가
  - 컴포넌트 만들 때 사용하시면 됩니다.
- `.svg` 파일들을 커스텀(`width`, `height`, `fill` 정해주는 것)하기 위해서는 7ce9208d1ebb7b0892f803534699d013b7face13 처럼 전처리가 필요합니다. 추후 아이콘 추가가 필요할 때 참고해주세요
  - 전처리: `width='current'`, `height='current'`, `fill='current'` 

### ⏰ Time Difference
- 총 8시 걸림

### 📝 Note
- 다시 생각해보니 text만 있는 버튼이니까 `plain`말고 `text` 도 괜찮을 거 같은데 의견 부탁드려요
- 추후 필요에 따라 다양한 `variant`를 추가할 수 있습니다. 일단 시안에 나온 버튼들의 `variant`만 만들었어요

2023-07-15 16:59 UTC, nangkyeonglim requested changes
컴포넌트 추상화 좋아요! text로 하는 것도 괜찮을 것 같아요
스토리북도 굉장히 잘 쓰여있어서 참고해서 쓰겠습니다👍

2023-07-15 16:59 UTC, nangkyeonglim commented on frontend/src/components/@common/Button/Button.stories.tsx
> +const meta = {
```suggestion
const meta: Meta<typeof Button> = {
```
이거 이렇게 쓰는거랑 satisfies 키워드 쓴 거랑 무슨 차이인지 궁금해요!

2023-07-15 16:59 UTC, nangkyeonglim commented on frontend/src/components/@common/Button/Button.tsx
> +  fontColor?: Color;
이거 두 개 지금 쓸 수 없는 거 같은데 없애는 거 어떤가요?

2023-07-15 16:59 UTC, nangkyeonglim commented on frontend/src/components/@common/Button/Button.tsx
> +        {Boolean(icon) && <S.IconWrapper size={size}>{icon}</S.IconWrapper>}
이거 어차피 icon 없으면 undefined인데 이렇게 써도 되지 않을까요?
```suggestion
        {icon && <S.IconWrapper size={size}>{icon}</S.IconWrapper>}
```

2023-07-15 16:59 UTC, nangkyeonglim commented on frontend/src/components/@common/Button/Button.tsx
> +      }
```suggestion
    primary: css`
      ${({ theme }) => `
        color: ${theme.color.gray10};
  
        background-color: ${theme.color.gray1};
        outline: 1px solid ${theme.color.gray1};
  
        &:hover {
          background-color: ${theme.color.primary};
          color: ${theme.color.gray2};
        }
  
        &:focus {
          box-shadow: 0 0 0 3px ${theme.color.primary};
        }
    `}
```
이거 theme 매번 가져오는 것보다 이렇게 쓰면 어떨까요?

2023-07-15 16:59 UTC, nangkyeonglim commented on frontend/src/components/@common/Button/Button.tsx
> +  IconTextContainer: styled.div<Props>`
이거 `<Props>` 빼줘도 되지 않을까요?

2023-07-16 09:15 UTC, jeonjeunghoon approved these changes
코드 보며 많이 배워갑니다 .......
대단한 컴포넌트를 탄생시켰네요
그저 감사합니다

2023-07-16 09:15 UTC, jeonjeunghoon commented on frontend/src/components/@common/Button/Button.tsx
> +      outline: 1px solid ${({ theme }) => theme.color.gray1};
outline은 rem으로 설정하지 않고 px로 설정한 이유가 궁금합니다

2023-07-16 15:56 UTC, yogjin commented on frontend/src/components/@common/Button/Button.tsx
> +  fontColor?: Color;
커밋 빼는 걸 깜박했네요.
짚어주셔서 감사합니다.

2023-07-16 16:00 UTC, yogjin commented on frontend/src/components/@common/Button/Button.tsx
> +        {Boolean(icon) && <S.IconWrapper size={size}>{icon}</S.IconWrapper>}
`icon`이 `undefined`인 경우 `undefined`는 falsy한 값이라 `false`인 `Boolean(icon)`과 동일하게 동작하겠지만,
저는 정확한 boolean 값을 이용하는게 좋다고 생각합니다. 
예상치 못한 동작을 막을 수 있기도 하고 더 직관적이라고 생각하는데, 어떻게 생각하시나요?

2023-07-16 16:02 UTC, yogjin commented on frontend/src/components/@common/Button/Button.tsx
> +      }
아 저런방법이 있군요?!?!
안그래도 쓰면서 되게 복잡하다고 생각했는데.. 
바로 반영하겠습니다😆

2023-07-16 16:05 UTC, yogjin commented on frontend/src/components/@common/Button/Button.tsx
> +export type Align = (typeof Align)[number];
공통 컴포넌트의 Variant, Size, Align 등이 정해진다면 그 때 빼도 좋을 것 같습니다.
(아직 디자인 시스템이 확립되지 않아서) 공통 컴포넌트들이 같은 type을 공유한다면 오류가 발생할 수도 있을 것 같아요.

2023-07-16 16:06 UTC, yogjin commented on frontend/src/components/@common/Button/Button.tsx
> +    ...rest
네 button 태그의 attribute 입니다.

2023-07-17 04:51 UTC, nangkyeonglim commented on frontend/src/components/@common/Button/Button.tsx
> +        {Boolean(icon) && <S.IconWrapper size={size}>{icon}</S.IconWrapper>}
흠.. 만약 count의 타입이 `undefined | number`라고 치면 조건문에서 Boolean 값을 이용하게 되면 0도 `false`로 동작하게 되는데 오히려 `count !== undefined` 이런식으로 아예 직관적으로 쓰는 건 어떤가요?

여기서는 icon은 무조건 `undefined | ReactElement`니까 `icon &&` 으로 쓰는것도 나쁘지 않다고 생각하긴 했는데 편한대로 써도 될 거 같아요!

2023-07-17 06:10 UTC, yogjin commented on frontend/src/components/@common/Button/Button.tsx
> +  IconTextContainer: styled.div<Props>`
습관적으로 작성했네요🙂
`Props`가 선언되어도 크게 성능차이는 없을 것 같아서 일단은 놔두겠습니다!

2023-07-17 06:20 UTC, yogjin commented on frontend/src/components/@common/Button/Button.stories.tsx
> +const meta = {
저도 스토리북에서 제공하는 테스트 파일을 가져다가 쓴거라 잘 모르겠네요😅
[satisfies 공식문서](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator)를 참고해주세요ㅎㅎ

2023-07-17 06:39 UTC, yogjin commented on frontend/src/components/@common/Button/Button.tsx
> +      outline: 1px solid ${({ theme }) => theme.color.gray1};
outline은 px로 고정해도 괜찮다고 판단했습니다.
또한 rem은 padding, margin, font-size에 적용하면 될 것 같아요.

2023-07-17 07:10 UTC, nangkyeonglim approved these changes
반영한 거 확인했습니다~ 고생하셨습니다

2023-07-17 07:11 UTC, merged