[BE] test: 테스트 커버리지 개선 및 테스트 격리
woowacourse-teams/2023-dong-gle pull request #501
Opened 2023-10-01 08:50 UTC by ingpyo

### 🛠️ Issue

- close #474 

### ✅ Tasks
- 테스트 커버리지 개선
- 테스트 코드 최적화

### ⏰ Time Difference
- 3day

2023-10-02 14:19 UTC, echo724 commented
My son,, holy moly oh my god.. 리뷰할 엄두가 안나는 작업량이네요 하느라 고생 많았네요,, 천천히 리뷰해보도록 하겠습니다

2023-10-04 08:38 UTC, HubCreator requested changes

2023-10-04 08:38 UTC, HubCreator commented on backend/src/test/java/org/donggle/backend/application/service/ModifyCategoryOrderTest.java
> +    private WritingRepository writingRepository;
이부분은... 롤백 해주세요!! 기존에 테스트 엣지 케이스를 제가 만들었었는데, 엣지 케이스에 대한 테스트가 지워졌어요ㅠㅠㅠ 그리고 이부분은 가능한 실제 환경에서 테스트하고 싶어요! 테스트의 일관성도 중요하지만, 무엇보다도 테스트로 무엇을 얻을 수 있는가와 테스트의 신뢰성을 여기서만큼은 보장하고 싶네요 ㅎㅎㅎ 저도 힘들게 만든건데... 남겨주세요 ㅠㅡㅠ

2023-10-04 08:38 UTC, HubCreator commented on backend/src/test/java/org/donggle/backend/application/service/writing/WritingServiceTest.java
> +        assertThat(response.map(WritingHomeResponse::createdAt).toList()).hasSize(12);
요런 것들은 실질적으로 레포지토리 계층에서 스프링 데이터 JPA가 Paging 처리를 잘 하고 있는지 보고 싶어서 만들었었어요. 또한 부가적으로 다음 페이지나 이전 페이지가 있는지, 현재 몇 페이지인지에 대한 검증도 했었는데... 없어졌어요ㅠㅠㅠ

2023-10-04 09:27 UTC, HubCreator commented on backend/src/test/java/org/donggle/backend/application/service/writing/WritingServiceTest.java
> +        assertThat(response.map(WritingHomeResponse::createdAt).toList()).hasSize(12);
비버의 노력이 너무 보이는 PR이네요! 너무 고생하셨습니다.💪🏻 다만 기존의 테스트에 영향이 있는 부분이 있어 확인해주시면 좋을 것 같아요.  추가로.. 말씀드리고 싶은건, 기존의 코드의 변경 대해서는 한 번 팀원들에게 얘기해주시면 좋을 것 같아요. 또한 PR의 단위가 매우 큰 편이어서, 부분적으로 이루어져도 좋았을 것 같네요 ㅎㅎㅎ 암튼 넘 고생하셨어요! 저도 테스트 케이스에 대해서 추가할 것이나 보완할 것 다시 보겠습니다. 😀

2023-10-04 10:08 UTC, ingpyo commented on backend/src/test/java/org/donggle/backend/application/repository/WritingRepositoryTest.java
> +    }
그러면 중복되는 부분이 없어질거같네요!

2023-10-04 10:08 UTC, ingpyo commented on backend/src/main/java/org/donggle/backend/ui/response/TistoryCategoryListResposnse.java
> +public record TistoryCategoryListResposnse(
아이공...

2023-10-04 10:08 UTC, ingpyo commented on backend/src/test/java/org/donggle/backend/application/repository/WritingRepositoryTest.java
> +    @DisplayName("영구삭제한을 제외한 글의 본문 내용과 함께 조회 테스트")
추가하겠습니다!

2023-10-04 10:08 UTC, ingpyo commented on backend/src/test/java/org/donggle/backend/application/repository/WritingRepositoryTest.java
> +    @DisplayName("해당 카테고리에 첫번째 글을 가져오는 테스트")
아 그렇네요 수정하겠습니다!

2023-10-04 10:08 UTC, ingpyo commented on backend/src/test/java/org/donggle/backend/application/service/writing/WritingServiceTest.java
> +        assertThat(response.map(WritingHomeResponse::createdAt).toList()).hasSize(12);
생성자의 대한 추가는 기존 로직에 대한 변경점이 없을거같아 그대로진행한거같네요... 다음부터는 말씀드리고 진행하겠습니다!

2023-10-06 07:51 UTC, echo724 approved these changes

2023-10-06 07:53 UTC, HubCreator approved these changes

2023-10-06 08:07 UTC, merged