[FE] `Ripple` 컴포넌트 추가
woowacourse-teams/2023-dong-gle pull request #505
Opened 2023-10-01 13:06 UTC by yogjin

### 🛠️ Issue

- close #503

### ✅ Tasks
- `Ripple` 컴포넌트 추가
- 스토리 추가

### ⏰ Time Difference
- 2 + 0

### 📝 Note
- 자신을 감싸는 컴포넌트에 물결이 퍼지는 효과를 부여하는 컴포넌트 입니다.
- 클릭으로 효과가 트리거됩니다.

https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/2d7b8b5d-b8e5-44ae-9536-a19dfef76b31

2023-10-02 08:45 UTC, jeonjeunghoon requested changes
스토리북에서 리플을 열심히 사용해봤는데 너무 좋더라구요!
디바운스도 걸려있고 여러 번 클릭해도 잘 동작하고 너무 좋아요

궁금한 부분은 코멘트에 추가해놨어요!
고생하셨어요~

2023-10-02 08:45 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +  cleanUpFunction: Function,
`Function` 을 사용한 이유는 어떤 형태의 함수가 들어올 지 정의가 안되어 그런걸까요?

2023-10-02 08:45 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +  const [rippleArray, setRippleArray] = useState<Ripple[]>([]);
해당 배열의 역할이 궁금해요

2023-10-02 08:45 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +  useLayoutEffect(() => {
`useEffect` 대신 `useLayoutEffect` 를 사용한 이유가 궁금합니다.
사용자의 마우스 위치 때문인가요?

2023-10-02 08:45 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +    const y = event.pageY - rippleContainer.y - size / 2;
이 친구들의 역할이 궁금해요...
제 추측엔
`x` 와 `y` 는 사용자의 마우스 위치인 것같은데 맞나요?
`size`는 어떤 역할인지 모르겠어요. 또한 `size / 2` 의 역할은 무엇인가요?

2023-10-02 08:45 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +        })}
rippleArray가 배열인 이유가 사용자가 빠르게 여러 번 클릭했을 때, 모든 효과들이 끊기지 않고 정상 동작하고 사라지도록 하기 위함인가요?

2023-10-02 08:45 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +import { Color } from 'styles/theme';
해당 객체는 사용되지 않고 있어요!

2023-10-02 08:45 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +  RippleContainer: styled.div<{ duration: number }>`
아마 `duration` 에 $ prefix를 붙이지 않으면 콘솔창에 에러 메시지가 발생할 것같아요

2023-10-02 12:46 UTC, nangkyeonglim requested changes

2023-10-02 12:46 UTC, nangkyeonglim commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +    return () => clearTimeout(bounce);
https://stackoverflow.com/questions/45802988/typescript-use-correct-version-of-settimeout-node-vs-window/56239226#56239226

저는 이글을 봤는데 그냥 아래처럼 `ReturnType<Type>`을 활용하면 node든 브라우저 환경이든 둘다 지원가능할 것 같아요!

그리고 밑에 아커코드에 &&bounce 조건문 있으면 영원히 조건문안으로 못들어오지않나요?

2023-10-03 02:46 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +    return () => clearTimeout(bounce);
오 같은 글을 봤네요! 해당 글에서도 다양한 의견들이 나온 것같아요

저는 동글이 node 환경을 지원해야 하는 이유를 모르겠어요...! 어떤 경우에 필요한가요??

그리고 다시 보니 && bounce 있으면 조건문 안에 못들어가네요...ㅠ

2023-10-03 02:57 UTC, nangkyeonglim commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +    return () => clearTimeout(bounce);
나중 이야기긴 하지만 서버사이드렌더링을 지원한다면..?

2023-10-04 08:41 UTC, jeonjeunghoon commented on frontend/src/components/@common/Ripple/Ripple.tsx
> +    return () => clearTimeout(bounce);
아앗..... 그렇다면 필요하겠네요

2023-10-10 01:23 UTC, closed without merging