[FE] feat: 티스토리 발행 카테고리 선택 기능, 발행 탭 블로그 연결 버튼 추가
woowacourse-teams/2023-dong-gle pull request #516
Opened 2023-10-03 14:08 UTC by yogjin

### 🛠️ Issue

- close #477
- close #515

### ✅ Tasks
- 티스토리 발행 시 카테고리 선택 기능
  - <img width="305" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/ebcaf597-6265-439b-b355-201869a74655">

- 발행 탭에 연결 블로그 없는 경우 마이 페이지로 이동하는 버튼 추가
  - 모든 블로그를 연결하지 않은 경우
    <img width="299" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/27180fdf-4819-47e1-b570-518f37d64cd3">
  - 하나만 연결한 경우
    <img width="329" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/7edafabb-bd7f-401a-b646-2c03d39babcd">
  - 모두 연결한 경우
    <img width="301" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/33623078/ed27f799-f2b7-4b44-b890-f3a36bfedd6b">

### ⏰ Time Difference
- 6 + 2

### 📝 Note

1. 카테고리 select `width`를 `100%`로 고정하고 싶은데 어떻게 해야할 지 모르겠네요ㅠ
2. <S.TistoryCategorySelect
              onChange={(e: ChangeEvent<HTMLSelectElement>) => setCategoryId(e.target.value)}
              disabled={isCategoryLoading}
            > 에서 onChange={(e: ChangeEvent<HTMLSelectElement>) => setCategoryId(e.target.value)} 이 부분이 의아할 수 있는데, styled로 select 태그를 쓰니까 `e` 타입을 감지못하더라구요. 그래서 저렇게 명시해두었습니다.

2023-10-04 07:47 UTC, nangkyeonglim requested changes
카테고리 없는 경우만 처리하면 좋을 것 같아요!

2023-10-04 07:47 UTC, nangkyeonglim commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +          <div>
select 크기 이 div에다가 `flex: 1` 주면 돼요(너무 꽉채운다 싶으면 `padding-right` 주기)

2023-10-04 07:47 UTC, nangkyeonglim commented on frontend/src/components/PublishingSection/PublishingSection.tsx
>    );
로직이 은근히 복잡한데 한글로 하니까 그나마 알아보기 쉽네요 굿

2023-10-04 07:50 UTC, yogjin commented on frontend/src/components/PublishingSection/PublishingSection.tsx
>    );
한글도 은근 괜찮죠? ㅋㅋㅋㅋㅋㅋ

2023-10-04 07:51 UTC, nangkyeonglim commented on frontend/src/components/PublishingSection/PublishingSection.tsx
>    );
ㅋㅋㅋㅋ 좋은데요

2023-10-04 08:42 UTC, yogjin commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +          <div>
반영했습니다~

2023-10-04 08:54 UTC, jeonjeunghoon requested changes
고생 많으셨습니다! 사용성이 더욱 개선되었네요 ㅎㅎ
궁금한 점 코멘트에 남겨뒀어요~!

2023-10-04 08:54 UTC, jeonjeunghoon commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +              {isCategoryLoading && <option hidden>불러오는 중입니다</option>}
오 option hidden 알아갑니다

2023-10-04 08:54 UTC, jeonjeunghoon commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +              {isCategoryLoading && <option hidden>불러오는 중입니다</option>}
근데 이런식으로 작성하면 저 옵션은 로딩 중이어도 안보이지 않나요??
제가 찾아본 바로는 hidden을 주면 셀렉박스에서 해당 옵션이 안보이는 것으로 알고 있어요

2023-10-04 08:54 UTC, jeonjeunghoon commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +                    </option>
서버에서 보내주는 `id` 는 무조건 0이 아닌 값이 오나요?
명세서에 해당 내용이 없어서 궁금해요

2023-10-04 08:54 UTC, jeonjeunghoon commented on frontend/src/components/PublishingSection/PublishingSection.tsx
>    );
진심 좋네요

2023-10-04 08:54 UTC, jeonjeunghoon commented on frontend/src/components/PublishingSection/PublishingSection.tsx
>    );
주석의 효과까지 있네요

2023-10-04 08:54 UTC, jeonjeunghoon commented on frontend/src/components/PublishingSection/PublishingSection.tsx
> +    gap: 2rem;
gap 에 rem 단위를 사용한 이유가 궁금합니다

2023-10-04 08:57 UTC, yogjin commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +              {isCategoryLoading && <option hidden>불러오는 중입니다</option>}
놀랍게도 보입니다..

2023-10-04 08:58 UTC, yogjin commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +                    </option>
넵 무조건 0이 아닌 값입니다
0은 `카테고리 없음`로 고정이에요

2023-10-04 08:59 UTC, yogjin commented on frontend/src/components/PublishingSection/PublishingSection.tsx
> +    gap: 2rem;
지금껏 `px`로 작성해왔었나요? 사실 큰 차이 없다고 생각해서 그냥 rem을 쓰긴 했는데..
언제 px, rem을 써야할지 기준이 좀 모호하네요..

2023-10-04 09:05 UTC, nangkyeonglim approved these changes
고생하셨습니다!

2023-10-05 12:35 UTC, jeonjeunghoon commented on frontend/src/components/PublishingPropertySection/TistoryPublishingPropertySection.tsx
> +              {isCategoryLoading && <option hidden>불러오는 중입니다</option>}
오호...! 좋은 정보 알아갑니다 ㅎㅎ

2023-10-05 12:35 UTC, jeonjeunghoon commented on frontend/src/components/PublishingSection/PublishingSection.tsx
> +    gap: 2rem;
저도 제 옛날 코드를 보니 px도 있고 rem도 있네요 ㅋㅋㅋ
이 부분 다시 한 번 잡고 가시죠!

2023-10-05 12:36 UTC, jeonjeunghoon approved these changes
고생하셨어요~!

2023-10-05 15:02 UTC, merged