[FE] fix: 휴지통 페이지 체크박스 버그 수정
woowacourse-teams/2023-dong-gle pull request #517
Opened 2023-10-03 15:29 UTC by jeonjeunghoon

### 🛠️ Issue

- close #511 

### ✅ Tasks
- [x] 체크박스 오류 해결

### ⏰ Time Difference
- 0.5 -> 0.5

### 📝 Note
Input 의 checked 속성이 defaultChecked로 수정되어 있더라구요.
이 부분에 checked를 추가하여 버그 해결했습니다.

https://github.com/woowacourse-teams/2023-dong-gle/assets/64737872/92574db8-4e82-4791-ad5f-5d44c8c70ad2

2023-10-04 07:57 UTC, nangkyeonglim requested changes
이거 예전에 쿠마가 console에 오류가 떠서 checked대신 default로 바꾼걸로 기억하는데
현재도 지금 콘솔에 오류가 뜨고있어요
checked는 onChange와 함께 써야된다고 써져있네요 

그리고 둘중 하나만 써야한다고 하네요 제어로 쓸것인지 비제어로 쓸것인지
<img width="583" alt="image" src="https://github.com/woowacourse-teams/2023-dong-gle/assets/57815133/6b6671c4-34f5-42c2-893d-699acf39c4de">

2023-10-04 08:35 UTC, nangkyeonglim commented
+) 현재 복구를 한번 하고 다른 글을 복구할 때 이전 복구된 writingId가 들어가고 있습니다.
한번 복구 후에 초기화를 시켜줘야할 것 같아요!

2023-10-05 04:33 UTC, nangkyeonglim requested changes
오오 잘동작하네요 굿입니다!

2023-10-05 04:33 UTC, nangkyeonglim commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
> +  const deletePermanentWritings = useDeletePermanentWritings(() => {});
이거 빈 함수 넣어주는 것보다 optional로 바꾸는 거 어떨까요?

2023-10-05 04:33 UTC, nangkyeonglim commented on frontend/src/components/TrashCanTable/useDeletePermanentWritings.ts
> +      onSuccessCbFn();
optional로 바꾸면 이부분이 onSuccessCbFn?.() 로 바꿔볼 수 있을것같아요!

2023-10-05 05:22 UTC, jeonjeunghoon commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
> +  const deletePermanentWritings = useDeletePermanentWritings(() => {});
아 이 부분을 PR에 적었어야 했는데 깜빡했네요
해당 컴포넌트는 GoToPageLink 컴포넌트가 생기면서 더이상 사용되지 않는 컴포넌트입니다!
따라서 해당 컴포넌트에 임시적으로 넣어뒀어요 ㅎㅎ

2023-10-05 05:23 UTC, jeonjeunghoon commented on frontend/src/components/TrashCan/DeletedWritingList.tsx
> +  const deletePermanentWritings = useDeletePermanentWritings(() => {});
그래서 머지가 되면 해당 파일은 지우고 머지시킬 것같습니다~!

2023-10-05 05:23 UTC, jeonjeunghoon commented on frontend/src/components/TrashCanTable/useDeletePermanentWritings.ts
> +      onSuccessCbFn();
이 부분도 위에 말씀 드린대로 수정할 필요 없을 것같아요~

2023-10-05 07:48 UTC, yogjin approved these changes
잘 동작하네요

2023-10-05 07:48 UTC, nangkyeonglim approved these changes
좋습니다 고생하셨습니다!

2023-10-05 08:06 UTC, closed without merging