[FE] 글 제목 수정 낙관적 업데이트 구현
woowacourse-teams/2023-dong-gle pull request #586
Opened 2023-10-16 12:17 UTC by yogjin

### 🛠️ Issue

- close #585

### ✅ Tasks
- 글 제목 수정할 때 낙관적 업데이트 적용
- 글 제목 수정 시 깜빡임 현상 해결
- 글 제목 수정 실패 테스트 추가 (msw 오버라이딩 환경설정 및 함수 추가)

### ⏰ Time Difference
- 6 + 6

### 📝 Note
-

2023-10-17 03:39 UTC, jeonjeunghoon requested changes
훅 분리랑 input value change 핸들러 내부에 넣는 의견 어떤가요?
코멘트로 남겨뒀어요~!

2023-10-17 03:39 UTC, jeonjeunghoon commented on frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx
> +      return { previousWritings, previousWritingsInCategory };
이 부분 잘 이해가 안가요.... 간략하게 설명 부탁드려요!

2023-10-17 03:39 UTC, jeonjeunghoon commented on frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx
> +          onChange={(e: ChangeEvent<HTMLInputElement>) => setInputTitle(e.target.value)}
`useControlledInput` 훅 내부에 핸들러가 있어도 될 것같다고 생각해요

2023-10-18 11:45 UTC, nangkyeonglim approved these changes
고생하셨어요! 바로바로 업데이트 되니까 좋네요

2023-10-18 11:45 UTC, nangkyeonglim commented on frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx
> +      return { previousWritings, previousWritingsInCategory };
이전 값을 저장해두고, 바로 queryClient로 상태를 업데이트 해주는 거에요.
여기서 이전 값을 저장해두는 context를 리턴하고 onError시에 이 context에 있는 previousWriting과 previousWritingsInCategory를 통해서 이전값으로 다시 롤백하는 역할을 해주는 것 같습니다

2023-10-18 12:28 UTC, yogjin commented on frontend/cypress.config.ts
> +    BASE_URL: 'https://dev.donggle.blog/api',
에러 테스트를 위해 `overrideWritingTitleWithError`으로 msw 핸들러를 오버라이딩할 때, 내부적으로 `~URL`을 사용합니다.
그 때 기존 process의 환경변수는 접근하지 못하더라구요.
아마 실행환경이 달라서 그런 것 같습니다.
그래서 불가피하게 cypress용 환경변수를 작성했습니다

2023-10-18 14:56 UTC, jeonjeunghoon commented on frontend/src/components/WritingViewer/WritingTitle/WritingTitle.tsx
> +      return { previousWritings, previousWritingsInCategory };
설명을 듣고 보니 이해가 잘 되네요 ㅎㅎ 자세한 설명 감사합니다~!

2023-10-19 12:37 UTC, merged